### ISSUE TITLE
Can I use Tobias to make non-pairwise comparisons?

### ISSUE THREAD

**Issue by Rosmaninho** [loosolab/TOBIAS#105]
Hey I have two different cell types across three compartments. 
Is it possible to use Tobias to determine differential binding between one variable independently of the other (cell types and compartments) (2 variables) as it is with edgeR for RNA-seq data (design matrix)?

**Comment by msbentsen** [comment]
Hi Rosmaninho,

I just want to make sure I understand you correctly - do you want to make a comparison something like this?
![image](https://user-images.githubusercontent.com/47495444/144207581-e37e4752-65b7-455c-944e-cf86cfd0067c.png)

Or only within celltypes / compartments?

**Comment by Rosmaninho** [comment]
I want to use a linear model to eliminate dependent variables when performing comparisons.
For instance, I have cell 1 in 3 compartments and cell 2 also in three compartments. For example, among other things, I want to perform the comparison between cell types without the different compartments confounding that comparison.

https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/factorial.html#a-linear-model-with-crossed-factors-estimates-interaction-effects

**Comment by msbentsen** [comment]
Ah, I understand now - no, that is unfortunately not possible with TOBIAS. If you run TOBIAS on the individual replicates, it might be possible to calculate the effect afterwards based on the mean footprint scores per TF, but it not something that I have tried out yet. Sorry! I hope you can find a solution nevertheless.
