### ISSUE TITLE
Customized motif bed files as BINDetect input

### ISSUE THREAD

**Issue by yyc0415** [loosolab/TOBIAS#106]
Hi Mette,

Thank you for developing this wonderful set of tools for fooptrint analysis. 

I am wondering if it is possible to integrate motifs with genomic sites as input for BINDetect to do differential TF analysis? 

An example would be the clustered motif sets from Vierstra et al., Nature 2020 (https://github.com/jvierstra/motif-clustering). They clustered motifs from different databases and generated genomic coordinates of each cluster's consensus motif. 

This would be very helpful as a lot of motifs from JASPAR or HOCOMOCCO are redundant. 

Thanks,
Leah

**Comment by msbentsen** [comment]
Hi Leah,

Thank you for your question - unfortunately, it is not possible right now, but it is a great idea! So just that I understand, you are looking for functionality to add something like `--precalc-TFBS TF1.bed TF2.bed <...>` to `TOBIAS BINDetect` and thus skip the input of motifs, and going directly to scoring the given input sites?

I will have to think about how to match this with the input `--peaks`, as these are used to calculate the background. So probably, it would contain a step of overlapping peaks to given TFBS.

I will add it here as "enhancement" and hope to get time to look at it soon 🙂 

BR Mette
