### ISSUE TITLE
Co-occupied with TF footprint.

### ISSUE THREAD

**Issue by tzhu-bio** [loosolab/TOBIAS#109]
Hi, thanks a lot for the TOBIAS.
Can I infer the co-occupied TF footprint with the output of TOBIAS.

**Comment by msbentsen** [comment]
Hi,

I am not 100% sure what you mean by co-occupied TF footprint - do you mean a motif co-occupied with a footprint or two motifs co-occupied with each other?

TOBIAS overlaps the positions of motifs with footprints to find locations of motif+footprint, but it is not yet possible to find the location of co-localized footprint+footprint or motif+motif. This is something that we are working on for another project, but is not yet available here, sorry.

Hope this answered your question!

Best Mette
