### ISSUE TITLE
Confidence for edges

### ISSUE THREAD

**Issue by RadPa** [loosolab/TOBIAS#117]
Hi,
Thank you for the TOBIAS.
I want to know if the edges created by TOBIAS CreateNetwork have confidence or weights. 

Good Day
Radhika

**Comment by RadPa** [comment]
If possible I would like to assign weights from `edges.txt`. But I am unable to do, can you please help?
Snippet from `edges.txt`. 
```
Sites_0	Sites_1	Sites_2	Sites_3	Sites_4	Sites_5	Sites_6	Sites_7	Sites_8	Sites_9	Sites_10	Sites_11	Sites_12	Sites_13	Sites_14	Sites_15	Sites_16	Sites_17	Sites_18	Sites_19	Sites_20	Sites_21	Sites_22	Sites_23	Sites_24	Origin_0	Origin_1
NC_047628.1	4237531	4237538	ABD-A_MA0206.1	7.3331	-	NC_047628.1	4236670	4240140	PEAK_11415	.	.	GENE	4229812.0	4235178.0	-	START	3227.0	UPSTREAM	0.0	0.0	LOC117564707		QUERY_1	0.2163	GCM2_MA0917.1	LOC117564707
NC_047628.1	4240035	4240040	CAUP_MA0217.1	5.61485	+	NC_047628.1	4236670	4240140	PEAK_11415	.	.	GENE	4229812.0	4235178.0	-	START	3227.0	UPSTREAM	0.0	0.0	LOC117564707		QUERY_1	0.26098000000000005	GCM2_MA0917.1	LOC117564707
```
Thank you
Radhika

**Comment by RadPa** [comment]
Thank you, Mette.
I checked with the TOBIAS test data and my data; for my data, I have used Site_24. The "edge weight"  i.e., Site_24 has low values (0.2), compared to the test data, 13 to 51. Is it something I need to worry about? 
Thank you for your time.
Radhika

**Comment by msbentsen** [comment]
Hi Radhika,
Good question, but no need to worry about that. The scores are high in the test data because it is normalized to a much lower genome size (only chr4). So scores of 0.2 are completely normal, and will always be in different ranges depending on the input data.
Best Mette

**Comment by RadPa** [comment]
Thanks a lot for all the help. 

Good Day
Radhika
