### ISSUE TITLE
snakemake example_config.yaml pipeline failed in writing all_motifs.txt 

### ISSUE THREAD

**Issue by mdu4003** [loosolab/TOBIAS#118]
Hello, 
We have installed TOBIAS successfully and we were trying to run the example to test the installation. 
We got an error in one of the output: all_motif.txt. 
I am attaching here the error: 

Error in rule format_motifs:
    jobid: 21
    output: test_output/motifs/all_motifs.txt
    log: test_output/logs/format_motifs.log (check log file(s) for error message)
    conda-env: /Users/taniadiaz/TOBIAS_snakemake/.snakemake/conda/515921b7dacb886a00dfa9677cd353de
    shell:
        TOBIAS FormatMotifs --input test_output/motifs/individual --format pfm --task join --output test_output/motifs/all_motifs.txt &>> test_output/logs/format_motifs.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/taniadiaz/TOBIAS_snakemake/.snakemake/log/2022-02-10T092822.786240.snakemake.log. 

Any advice?

[2022-02-10T092822.786240.snakemake.log](https://github.com/loosolab/TOBIAS/files/8042207/2022-02-10T092822.786240.snakemake.log)

**Comment by msbentsen** [comment]
Hi,
It seems like the rule "format_motifs" is failing. Can you post the log-file coming from this rule (**test_output/logs/format_motifs.log**)? That might show why it has an issue, thanks!

**Comment by msbentsen** [comment]
Oh, I see... hmm yes, that seems a bit weird. Just to debug, is it possible for you to activate the conda environment with:
` conda activate /Users/taniadiaz/TOBIAS_snakemake/.snakemake/conda/515921b7dacb886a00dfa9677cd353de`

And then run the shell command as listed by the snakemake pipeline: 
`TOBIAS FormatMotifs --input test_output/motifs/individual --format pfm --task join --output test_output/motifs/all_motifs.txt`

That should write out any logs/error messages to the commandline. Also, can you provide some info on the system you are on? Thanks!

**Comment by mdu4003** [comment]
Hello, 
We run the command as you said after activating conda with that line and now we got an input. 
I am copying here the shell and attaching the file. 
It seems it run without error. I do not quite understand why it does not run in the whole pipeline?
Thank you very much for your help. 

(base) taniadiaz@MAC205934 ~ % conda activate /Users/taniadiaz/TOBIAS_snakemake/.snakemake/conda/515921b7dacb886a00dfa9677cd353
(/Users/taniadiaz/TOBIAS_snakemake/.snakemake/conda/515921b7dacb886a00dfa9677cd353de) taniadiaz@MAC205934 ~ % TOBIAS FormatMotifs --input /Users/taniadiaz/TOBIAS_snakemake/test_output/motifs/individual --format pfm --task join --output /Users/taniadiaz/TOBIAS_snakemake/test_output/motifs/all_motifs.txt
# TOBIAS 0.13.2 FormatMotifs (run started 2022-02-14 09:16:50.912290)
# Working directory: /Users/taniadiaz
# Command line call: TOBIAS FormatMotifs --input /Users/taniadiaz/TOBIAS_snakemake/test_output/motifs/individual --format pfm --task join --output /Users/taniadiaz/TOBIAS_snakemake/test_output/motifs/all_motifs.txt

# ----- Input parameters -----
# input:	['/Users/taniadiaz/TOBIAS_snakemake/test_output/motifs/individual']
# output:	/Users/taniadiaz/TOBIAS_snakemake/test_output/motifs/all_motifs.txt
# format:	pfm
# task:	join
# filter:	None
# verbosity:	3
[all_motifs.txt](https://github.com/loosolab/TOBIAS/files/8061613/all_motifs.txt)


# ----- Output files -----
# /Users/taniadiaz/TOBIAS_snakemake/test_output/motifs/all_motifs.txt


2022-02-14 09:16:50 (51872) [INFO]	Reading input files...
2022-02-14 09:16:51 (51872) [INFO]	Read 86 motifs

2022-02-14 09:16:51 (51872) [INFO]	Writing converted motifs to file /Users/taniadiaz/TOBIAS_snakemake/test_output/motifs/all_motifs.txt

2022-02-14 09:16:51 (51872) [INFO]	Finished FormatMotifs run (total time elapsed: 0:00:00.170575)

**Comment by msbentsen** [comment]
That is indeed strange! But now since it ran through, you should be able to run the original snakemake command again, since the output is already there. Does that work?

I am not sure why it happens (maybe an issue coming from snakemake), so a work-around is always to run the command manually.
