### ISSUE TITLE
What does the columns mean in edges.txt from CreateNetwork?

### ISSUE THREAD

**Issue by smallfade** [loosolab/TOBIAS#12]
All columns are named as Site N, which is quite meaningless. Can anyone help to explain a bit? Or provide some instruction on how to show the network correctl in Cytoscape. Thanks!

**Comment by msbentsen** [comment]
I agree that the column-names are not very informative - sorry about that! The column names in `edges.txt` basically state the column number from the sites (e.g. the --TFBS input) and the column number from the origin information (e.g. --origin). I will have a look at improving this in a future release of TOBIAS.

For now, it might be easier for you to load the individual `<TF>_path_edges.txt` files. Here, the column header gives the `Source` and `Target` columns directly. To load the network in Cytoscape, you have to select File -> Import -> Network from file. With both `edges.txt` and `<TF>_path_edges.txt`, you have to select the correct source/target columns. For `edges.txt`,  `Source` is going to be the name of the TF binding (sites_3 in most cases) and `Target` is going to be the target gene (Origin_0). Hope this answers your question!

**Comment by smallfade** [comment]
> I agree that the column-names are not very informative - sorry about that! The column names in `edges.txt` basically state the column number from the sites (e.g. the --TFBS input) and the column number from the origin information (e.g. --origin). I will have a look at improving this in a future release of TOBIAS.
> 
> For now, it might be easier for you to load the individual `<TF>_path_edges.txt` files. Here, the column header gives the `Source` and `Target` columns directly. To load the network in Cytoscape, you have to select File -> Import -> Network from file. With both `edges.txt` and `<TF>_path_edges.txt`, you have to select the correct source/target columns. For `edges.txt`, `Source` is going to be the name of the TF binding (sites_3 in most cases) and `Target` is going to be the target gene (Origin_0). Hope this answers your question!

It helps! Thanks a lot! And thank you for this tool, I think TOBIAS is awesome!

**Comment by lynnyummy** [comment]
Hi, I just want to double check I can only reconstruct the network based on the TFs we found, right? the motif2gene file means we need to find out the TF corresponding gene ID in the genome, is it right?

Thank you very much!

> I agree that the column-names are not very informative - sorry about that! The column names in `edges.txt` basically state the column number from the sites (e.g. the --TFBS input) and the column number from the origin information (e.g. --origin). I will have a look at improving this in a future release of TOBIAS.
> 
> For now, it might be easier for you to load the individual `<TF>_path_edges.txt` files. Here, the column header gives the `Source` and `Target` columns directly. To load the network in Cytoscape, you have to select File -> Import -> Network from file. With both `edges.txt` and `<TF>_path_edges.txt`, you have to select the correct source/target columns. For `edges.txt`, `Source` is going to be the name of the TF binding (sites_3 in most cases) and `Target` is going to be the target gene (Origin_0). Hope this answers your question!

**Comment by msbentsen** [comment]
Hi @lynnyummy,
Yes correct - we need the motif2gene file since the network has to know what the linkage is between a gene and its gene product. And this can only be done for those TFs which also have motif positions in the genome.

**Comment by lynnyummy** [comment]
> Hi @lynnyummy,
> Yes correct - we need the motif2gene file since the network has to know what the linkage is between a gene and its gene product. And this can only be done for those TFs which also have motif positions in the genome.

Okk! Thanks @msbentsen ! I will try them~ thank you so much!
