### ISSUE TITLE
TFBS_score 

### ISSUE THREAD

**Issue by ikumar2000** [loosolab/TOBIAS#122]
What are TFBS_score based on? Does the tool use TOMTOM or something similar? Is there any guideline for considering a good TFBS score to select only high confidence motif match?

**Comment by msbentsen** [comment]
Hi,

The TFBS_score is calculated using the MOODS library (https://github.com/jhkorhonen/MOODS), which works by matching each motif against the genome sequence, and writing if there was a significant hit. The scores are dependent on the motif, so it is not possible to directly compare TFBS_score between motifs. Instead, the threshold for a good TFBS score is decided by the p-value threshold (`--motif-pvalue`). This is already set at 1e-4 to highlight high confidence matches, but if you need to, you can set the p-value stricter to get less motif matches. Hope this answers your question!
