### ISSUE TITLE
TOBIAS BINDetect

### ISSUE THREAD

**Issue by pericles-pendragon** [loosolab/TOBIAS#123]
Hello. Im very interested to use TOBIAS for my ATAC-seq data. I have the bw footprinting files. But in BINDetect I have an error:
"11679) [ERROR]	Region "chrUn_DS484314v1	1411	2410" is outside of the chromosome boundaries (chrUn_DS484314v1: 2381)"
I'm using drosophila melanogaster genome (dm6.fa from UCSC).

Hope you can help me.
Here is the link with the files:
[https://drive.google.com/file/d/1LosHrvgL2s6lXMK6jOVfRpo-ukbE3HBF/view?usp=sharing](url)

**Comment by msbentsen** [comment]
Hi,

Thank you for sending the files! I think the error already describes the issue - that a region is outside of the boundaries. An input region in the `Merge-narrow-peaks.bed` has coordinates 1411-2410, but that contig (chrUn_DS484314v1) is only 2381 bases long according to the fasta genome file. 

How did you create the peaks file? Maybe there is a mismatch between the genomes used at different steps of the pipeline.

**Comment by pericles-pendragon** [comment]
Hello.
I merged the narrow peaks from the two conditions to test using bedtools . There is another way or I have a wrong understand?
Thanks for your answer.

**Comment by msbentsen** [comment]
I think the issue is, that the peak-calling is reporting peaks outside of the boundaries of the genome (which should not be possible). Maybe this is an effect of the peak-caller you used (before using bedtools)? 

In any case, you need to make sure that your peaks are within the chromatin boundaries in order to use BINDetect.

**Comment by pericles-pendragon** [comment]
Thanks for your assistance. 
I runed again the peak caller (MACS2) but masking the contings (chrUn_XXXXXXXX) and it worked fine. Last question, is ok using merge function from bedtools? What if I use intersect of all peaks?
Regards

**Comment by msbentsen** [comment]
Hi, 

Super, glad it worked out. And yes, it is totally fine to use the merge function to get the intersect of all the peaks - this will ensure that you include peaks from all samples/conditions, thus including all regions of interest in the run. I would recommend that as well.

BR Mette
