### ISSUE TITLE
motifs2gene file generation

### ISSUE THREAD

**Issue by odagayev** [loosolab/TOBIAS#125]
HI!

Do you have tips on how to generate the motif2gene file? 

Can you provide any information on how the motif2gene file was generated for the tutorial dataset? 

Thank you!

**Comment by msbentsen** [comment]
Hi,

For the tutorial dataset, we correlated TF names with gene ids via [ensembl](https://www.ensembl.org/index.html). You can fetch information for each gene in the human genome and subset it based on the TF names in JASPAR. For HOCOMOCO motifs, they also provides an annotation file (downloads->complete model annotation: [annotation_HUMAN_mono.tsv](https://hocomoco11.autosome.org/final_bundle/hocomoco11/core/HUMAN/mono/HOCOMOCOv11_core_annotation_HUMAN_mono.tsv)), but then you have to convert EntrezGene ids to ensembl depending on what gene ids are in your annotation .gtf. 

Most importantly, the file just has to have one column with motif names (fitting the output of BINDetect) and one column with the gene id/name (fitting to the annotation .gtf-file used). I did it rather manually (own scripts etc.) in the past, so sorry I cannot be of more help.

BR Mette

**Comment by odagayev** [comment]
Got it - thank you!
