### ISSUE TITLE
BINdetect, or?

### ISSUE THREAD

**Issue by araposo-cantab** [loosolab/TOBIAS#128]
Dear TOBIAS, 
How can use your tool without a motif database? 
Eg, BINDetect (or another, more appropriate module) with no --motifs parameter.

Why? I'm interested in identifying, mapping and scoring footprints, and calculate differential binding between two conditions without the limitations of current annotation.

Cheers,
Alexandre

**Comment by msbentsen** [comment]
Hi Alexandre

In the BINDetect model, it is just a simple log2(condition1+pseudocount / condition2+pseudocount) where pseudocount is an appropriate pseudocount (alike to +1 for expression data). This is then compared per TF towards the distribution of background log2FCS (same calculation for a random selection of regions), to control for global differences between condition1/2 footprint strength.

I have had requests for the experimental design matrix before, and it would be amazing to include! But the implementation would unfortunately be quite complex in the current setup, and we have no plans to include that at the moment. Again, you might access the raw footprint scores and setup the design yourself - although this unfortunately comes with a bit of coding, sorry!
