### ISSUE TITLE
Whats the difference between ScoreBigwig and FootprintScores?

### ISSUE THREAD

**Issue by Danvor** [loosolab/TOBIAS#13]
The two commands seem to have the same help messages too, is there any difference between them?

**Comment by msbentsen** [comment]
There is no difference! The double-naming is purely for the purpose of backward compatibility, as we changed the name from FootprintScores to ScoreBigwig in TOBIAS 0.4.0 ([as seen in CHANGES](https://github.com/loosolab/TOBIAS/blob/master/CHANGES)). Both commands now link to 'TOBIAS ScoreBigwig'. I should add this to the description though :-)

**Comment by msbentsen** [comment]
I have included a note on this in the `ScoreBigwig` help message of the new release `TOBIAS 0.11.1`.
