### ISSUE TITLE
user defined heatmap color in TOBIAS PlotHeatmap 

### ISSUE THREAD

**Issue by raunakms** [loosolab/TOBIAS#130]
In `TOBIAS PlotHeatmap` function, is it possible to add an argument for user defined color set instead of using the default `cmap="seismic"` ?

**Comment by msbentsen** [comment]
It is not possible at the moment, but I agree, that would be a nice addition! Looks pretty easy to include as a commandline parameter `--cmap`, so I will have a look at including that some time this week or maybe next.

Note to self, choice of cmap is here: 
https://github.com/loosolab/TOBIAS/blob/df1c72f9c0546fa65369e92b9534ed5bb9d885a6/tobias/tools/plot_heatmap.py#L329

**Comment by msbentsen** [comment]
Hi,

I just added a commit to the dev-branch with this functionality (https://github.com/loosolab/TOBIAS/commit/50e03aa97e39fef6edc0f6c23ee5b1e9dc740fb1). I like to collect a few changes before releasing an official version, but until then, you can install the version using:
`pip install git+https://github.com/loosolab/TOBIAS@dev`

Running `TOBIAS --version` should confirm the version to be `0.14.0-b`. Hope this helps you out!
