### ISSUE TITLE
BINDetect gets stuck while loading motifs

### ISSUE THREAD

**Issue by thijs32** [loosolab/TOBIAS#131]
Hi Mette! Thank you for creating this amazing package of programs, I have been able to make great use of it already!

I have run into a problem sadly, and I was hoping that you could maybe help me out.

When I run the BINDetect command, the program keeps running forever after printing "Reading 250 motifs from file", it is supposed to print "Creating folder structures for each TF" next, but never gets to this point. The program does not give me any errors.
I added some debugging print lines to the script and found that line 270 does not work.

I have tried running it on more cores and getting a different motif file in a different format, but none of this seems to help. I have been able to run the command successfully before, but haven't been able to repeat it strangely enough.

So I was wondering if you have any idea why the script would stop working here? Any help would be immensely appreciated!

all the best,
Thijs

**Comment by msbentsen** [comment]
Hi Thijs,

Sorry about this error - can you provide a little more information on the system you are on + what python version you are using? I noticed that the line performs multiprocessing:
https://github.com/loosolab/TOBIAS/blob/df1c72f9c0546fa65369e92b9534ed5bb9d885a6/tobias/tools/bindetect.py#L270 

There was recently an issue written regarding multiprocessing on python>3.7 on Mac systems, so maybe this is also the issue in this case?

**Comment by thijs32** [comment]
Hi, thanks for your response!

We are running python 3.9.7. on a Linux CentOS 7 server.
I have run the command on 8 cores with 12 gb of memory, if that is relevant information.

I will look into the multiprocessing for sure. I hope that could fix it.
