### ISSUE TITLE
Use of CreateNetwork

### ISSUE THREAD

**Issue by pericles-pendragon** [loosolab/TOBIAS#133]
Hello.
Ihave been using TOBIAS with great results.
Anyway, I want to use CreateNetwork tool, but I 'dont understand the input files, and I can't find the example file "motif2gene_mapping.txt". If you could provide the example file or another advice I would be very grateful.
Regards

**Comment by msbentsen** [comment]
Hi,

That is indeed a bit poorly explained in the documentation, sorry about that. You can find the `motif2gene_mapping.txt` file as the output of `TOBIAS DownloadData`. It has the format:
```
Alx1    ENSG00000180318
ALX3    ENSG00000156150
Alx4    ENSG00000052850
Ar      ENSG00000169083
AR      ENSG00000169083
ARGFX   ENSG00000186103
Arid3a  ENSG00000116017
Arid3b  ENSG00000179361
Arid5a  ENSG00000196843
ARNT2   ENSG00000172379
```

Where the first column is the TF name as given in the TFBS files, and the second column is the corresponding gene name. I created it by querying ensembl and assigning the JASPAR motifs to the gene ids, but it should be easily extendable with new names. Hope this is helpful!

BR Mette

**Comment by pericles-pendragon** [comment]
Thanks for your answer. Its more clear. 
I have another issue. The annotation peaks is in a bed file? I've already annotate the bed files with homer, but in what column the gene name should be annotated? Or what structure must have the annotation file from the bed?
Regards

**Comment by msbentsen** [comment]
Yes, the input TFBS should be annotated, but it doesn't matter in which column the annotation lies. The 4th column must contain the TF name (for each site as output by TOBIAS), but then the annotation (with the gene fitting to the motif2gene_mapping.txt), can be in any column e.g.:
```
chr4    330112  330129  Alx1     7.09664 -       (...)        ENSG1
chr4    742894  742911  Alx1     5.34296 -       (...)        ENSG2
chr4    1073091 1073108 Alx1     5.78309 +       (...)        ENSG3
````

There are some checks built into CreateNetwork, so it should complain during the run if the input is not fitting.

**Comment by pericles-pendragon** [comment]
That example was illustrative. Thanks a lot.

Regards
