### ISSUE TITLE
PlotTracks can't plot the gene pattern

### ISSUE THREAD

**Issue by Eric-tsc** [loosolab/TOBIAS#136]
Hello,
        Thanks you for developing so useful tool, and I have question in PlotTracks, the coordinate of the gene is shown as N/A. I provide all input file, and I'm sure the process is all right, but the result plots can't creat gene pattern (other parts are normal). The gtf file was downloaded from [Ensemb](https://www.ensembl.org/index.html), but it's only include "transcript_id" and "gene_id" in the eighth column, because it's belong the plants and the annotation is not perfect. Do you have any advice on these question?

**Comment by msbentsen** [comment]
Hi, 
Thank you for your interest in the tool. Can you share a few lines of the .gtf file with me? I am not very familiar with plant annotations, so I might have made certain assumptions in the tool, which are not valid for all organisms. Then I can try to provide a fix for you. Thank you!

**Comment by Eric-tsc** [comment]
Hi,
&nbsp; &nbsp; Thanks for your reply!
&nbsp; &nbsp; The&nbsp;attachment includes the annotation file of banana, the musa_acuminata_v2.gff3 (DH Pahang) was downloaded from https://banana-genome-hub.southgreen.fr,&nbsp;
while the Musa_acuminata_ensembl.gtf was downloaded from ensembl plants.
best wish,Eric




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "loosolab/TOBIAS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月16日(星期一) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [loosolab/TOBIAS] PlotTracks can't plot the gene pattern (Issue #136)





 
Hi,
 Thank you for your interest in the tool. Can you share a few lines of the .gtf file with me? I am not very familiar with plant annotations, so I might have made certain assumptions in the tool, which are not valid for all organisms. Then I can try to provide a fix for you. Thank you!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;



从QQ邮箱发来的超大附件

Musa_acuminata_ensembl.gtf (62.70M, 2022年06月15日 16:47 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7e356461edff71cf8f0989771e39571c08070603595a52051c5351580c145105070d49030c5b561e08500054595c5555540554563823657e4446053e595a105e585b05155966005d4250090354170247573559&code=15da89e3




musa_acuminata_v2.gff3 (83.66M, 2022年06月15日 16:47 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=2d366163b758f5c2d80a8c75113902175453515a0100010b4b0e02520f14040d51534c5a075c00155f045854035a030f00525054372f30551345003c565a45550f5800175666460a4851070504390d&code=f6ac7908




musa_acuminata_v2.gtf (65.64M, 2022年06月15日 16:47 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7e3233336288d7c98a0ede251136001d55560b030306045419035152051b060200511e520253071f0d56500202050b54010202053723325f4141526c5655475f5d5c5247566944001a554755370b&code=42337622

**Comment by msbentsen** [comment]
Hi @Eric-tsc, can you share the direct link to these files or send the attachments to my email mette.bentsen (at) mpi-bn.mpg.de? I can't see the attachments from the github answer. Thanks!

**Comment by Eric-tsc** [comment]
Hi,
&nbsp; &nbsp;&nbsp;Thanks for your reply!
&nbsp; &nbsp; You can download the *.gff3 file from https://banana-genome-hub.southgreen.fr/filebrowser/download/7819625&nbsp;or&nbsp;http://ftp.ensemblgenomes.org/pub/plants/release-53/gff3/musa_acuminata


Best wish,
Eric




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mette ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 晚上6:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [loosolab/TOBIAS] PlotTracks can&#39;t plot the gene pattern (Issue #136)





 
Hi @Eric-tsc, can you share the direct link to these files or send the attachments to my email mette.bentsen (at) mpi-bn.mpg.de? I can't see the attachments from the github answer. Thanks!

**Comment by Eric-tsc** [comment]
Hi, 
Thanks for your reply! My input file was aways gtf format. The download file from the links were gff format, but I had convert gff to gtf by gffread genome.gff3 -T -o genome.gtf. In addition, I also tried to use gff3ToGenePred and genePredToGtf tools to convert between gff and gtf, but the PlotTracks hasn't been ploting the gene pattern properly.
such as:
(https://user-images.githubusercontent.com/61375704/169426861-63f068df-cc33-48af-9220-f94c00f2ea8b.png)

**Comment by msbentsen** [comment]
Ah okay, I see. Can you share a few lines of the converted .gtf file with me then? Perhaps those you expected to see in the region of the plot?

Then I can better test why it is not working. Thank you!

**Comment by Eric-tsc** [comment]
Hi,
Thanks for your reply! I have solved these problem by adjusting the parameters during convert gtf process, the gtf file needs to contain transcript coordinate information, thanks for your advices.
Best wish!

**Comment by msbentsen** [comment]
I see, thank you for the update! PlotTracks could definitely handle that better, so I will shift it back to "enhancement" for a future look at some better error messages. So I will close this, but please reopen if the issues remain.

**Comment by xiaodaidaidai** [comment]
Hello, I also encountered this error while using this software. Could you please provide a few lines of sample data for GTF? Thank you very much

**Comment by mohobein** [comment]
Hey @xiaodaidaidai, a functioning gtf file can be found in the test data provided [here](https://github.com/loosolab/TOBIAS/wiki/test-data). After downloading the directory, the file is located at `test_data/genes.gtf`.

Here is the first line as an example:
`chr4    havana  gene    49096   50124   .       -       .       gene_id "ENSG00000248302"; gene_version "3"; gene_name "BNIP3P41"; gene_source "havana"; gene_biotype "transcribed_processed_pseudogene";`

Explanations for the columns can be found [here](https://www.ensembl.org/info/website/upload/gff.html).

I hope this suffices to find your problem. If not, feel free to tell us more about the error you are encountering.

Best regards,
Moritz

**Comment by xiaodaidaidai** [comment]
Dear Moritz,
 
I hope this message finds you well. Your guidance and provision of the functioning GTF file located in the test data directory were invaluable in rectifying the problem I encountered.  By referencing the example line you provided and the explanations for the columns, I was able to identify and address the error efficiently. Your clear instructions and willingness to assist made the process much smoother.
 
Once again, thank you for your assistance. 
 
Best regards,
xiaodaidai





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "loosolab/TOBIAS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月26日(星期二) 晚上7:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [loosolab/TOBIAS] PlotTracks can't plot the gene pattern (Issue #136)





 
Hey @xiaodaidaidai, a functioning gtf file can be found in the test data provided here. After downloading the directory, the file is located at test_data/genes.gtf.
 
Here is the first line as an example:
 chr4    havana  gene    49096   50124   .       -       .       gene_id "ENSG00000248302"; gene_version "3"; gene_name "BNIP3P41"; gene_source "havana"; gene_biotype "transcribed_processed_pseudogene";
 
Explanations for the columns can be found here.
 
I hope this suffices to find your problem. If not, feel free to tell us more about the error you are encountering.
 
Best regards,
 Moritz
