### ISSUE TITLE
Single-cell ATACseq 

### ISSUE THREAD

**Issue by annrosebright** [loosolab/TOBIAS#137]
Hi,

Thanks for this great tool. Is it possible to run Tobias on single-cell ATAC-seq data or clusters derived from single-cell data analysis? If there is any workaround possible that would be great. 

Best,
Ann

**Comment by msbentsen** [comment]
Hi Ann,

It is unfortunately not possible to directly input single cell data to TOBIAS, but we have had success in the past with pseudo-bulking clusters as you mention. What we did was just to split all scATAC fragments into the groups to which the source cells were clustered, which emulates the idea of a bulk experiment. 

What type of data are you working with? 10X? I might be able to provide a script for doing the initial splitting. 

Best Mette

**Comment by annrosebright** [comment]
Hi Mette,

Yes, our data is 10x and I have analyzed the data using ArchR. I tried to extract cluster cell names and then split the bam file as follows.  

#Text file with cell names = res0.2_C5.txt 
# Save the header lines
samtools view -H test.bam > SAM_header
# Filter alignments using filter.txt. Use LC_ALL=C to set C locale instead of UTF-8
samtools view test.bam | LC_ALL=C grep -F -f res0.2_C5.txt > filtered_SAM_body
# Combine header and body
cat SAM_header filtered_SAM_body > filtered.sam
# Convert filtered.sam to BAM format
samtools view -b filtered.sam > filtered.bam

I am not sure if this is the right way to do it. it. If you could provide a better script or easier way to do the spitting it would be great. 

Best,
Ann

**Comment by msbentsen** [comment]
Hi Ann,

I suppose that the `res0.2_C5.txt` contains the cell names for one cluster (cluster 5)? And that you then get a `filtered.bam` for every cluster in the end? In that case, your way of doing it is perfect!

Then, you can use the individual `cluster1.bam`, `cluster2.bam`, etc. as conditions for peak calling and TOBIAS analysis.

Best Mette

**Comment by jiayuzh** [comment]
> Hi Ann,
> 
> It is unfortunately not possible to directly input single cell data to TOBIAS, but we have had success in the past with pseudo-bulking clusters as you mention. What we did was just to split all scATAC fragments into the groups to which the source cells were clustered, which emulates the idea of a bulk experiment.
> 
> What type of data are you working with? 10X? I might be able to provide a script for doing the initial splitting.
> 
> Best Mette

Hi Mette,

I'm working with scATAC-seq data in a project and I would like to apply TOBIAS . I'd love to learn about your recommended way to do the pseudo-bulking. Could you share?

Thanks,
Jiayu

**Comment by hcph** [comment]
How about to get the bam file through peak.bed file using the following command:
bedtools bedtobam -i "$i".bed -g genome_table.txt >"$i".bam

**Comment by msbentsen** [comment]
> How about to get the bam file through peak.bed file using the following command: bedtools bedtobam -i "$i".bed -g genome_table.txt >"$i".bam

Hi @hcph,

No, this approach will not work, as the .bam-file has to contain reads from ATAC-seq (or scATAC-seq) and not the regions from the .bed-file. The .bed-file is usually the result of peak-calling on the .bam-files, so the other way around is not possible.

BR Mette

**Comment by yuyan415** [comment]
Hi Mette,

I wonder when you subset bam by cell clusters, do you use the possort.bam generated by cell ranger? Once you subset, do you remove the duplicated reads before running TOBIAS? 

Thanks!

**Comment by yuyan415** [comment]
> Hi @jiayuzh ,
> 
> My recommendation would be to start by clustering the cells from your single cell experiment, and thus receiving a form of `cell barcode -> cluster name` list, e.g.:
> 
> ```
> barcode1  cluster1
> barcode2  cluster1
> barcode3  cluster2
> ```
> 
> Then you can create individual .bam-files containing only reads from cluster1, cluster2, etc. (for example using Ann's commands above) such that you have:
> 
> ```
> cluster1.bam     
> cluster2.bam
> (...)
> ```
> 
> These can then be used as input to TOBIAS as different conditions.

Hi Mette,

I wonder when you subset bam by cell clusters, do you use the possort.bam generated by cell ranger? Once you subset, do you filter low-quality and duplicated reads before running TOBIAS?

Thanks!

**Comment by yuyan415** [comment]
> Hi @jiayuzh ,
> 
> My recommendation would be to start by clustering the cells from your single cell experiment, and thus receiving a form of `cell barcode -> cluster name` list, e.g.:
> 
> ```
> barcode1  cluster1
> barcode2  cluster1
> barcode3  cluster2
> ```
> 
> Then you can create individual .bam-files containing only reads from cluster1, cluster2, etc. (for example using Ann's commands above) such that you have:
> 
> ```
> cluster1.bam     
> cluster2.bam
> (...)
> ```
> 
> These can then be used as input to TOBIAS as different conditions.

Hi Mette,

I wonder when you subset bam by cell clusters, do you use the possort.bam generated by cell ranger? Once you subset, do you filter low-quality and duplicated reads before running TOBIAS?

Another question: I think during ATACorrect, TOBIAS normalize by read-depth. In that case is it okay to compare footprinting among sub-cluster bams with different number of reads?

Thanks!

**Comment by yuyan415** [comment]
> Hi @jiayuzh ,
> 
> My recommendation would be to start by clustering the cells from your single cell experiment, and thus receiving a form of `cell barcode -> cluster name` list, e.g.:
> 
> ```
> barcode1  cluster1
> barcode2  cluster1
> barcode3  cluster2
> ```
> 
> Then you can create individual .bam-files containing only reads from cluster1, cluster2, etc. (for example using Ann's commands above) such that you have:
> 
> ```
> cluster1.bam     
> cluster2.bam
> (...)
> ```
> 
> These can then be used as input to TOBIAS as different conditions.

Hi Mette,

I wonder when you subset bam by cell clusters, do you use the possort.bam generated by cell ranger? Once you subset, do you filter low-quality and duplicated reads before running TOBIAS?

Another question: I think during ATACorrect, TOBIAS normalize by read-depth. In that case is it okay to compare footprinting among sub-cluster bams with different number of reads, or would you recommend getting same amount of reads from each sub-cluster bam first, and then run TOBIAS?

Thanks!

**Comment by msbentsen** [comment]
Hi @yuyan415 ,

Yes exactly, I would filter out duplicates before running TOBIAS. I don't often work with cellranger, so I am not sure what the possort.bam contains, but the .bam-file should be one containing all reads from all cells - which can then be subset per cluster.

Regarding read depth, TOBIAS normalizes for this, so it is fine to compare footprinting among subclusters with different number of cells/reads. Just be aware that very small clusters might create a signal too sparse to find footprints, which is not something that can be normalized by read depth. I don't have a lower bound for minimum number of cells, but you can have a look at the output footprints to check this. 

Hope that helps you out!

BR Mette

**Comment by yuyan415** [comment]
Thank you @msbentsen Mette, for the quick response! This is very helpful.
