### ISSUE TITLE
Headers of the bed files generated by BIND DETECT

### ISSUE THREAD

**Issue by odagayev** [loosolab/TOBIAS#138]
Hi!

Thank you for publishing this module!

I was wondering, do you have explicit documentation anywhere for the bed file ouputs from BIND DETECT?

I can understand what the first 6 columns are  (chromosome, start, end, motif, score, strand) - but am having trouble understanding what the last 4 columns of the bed file mean. 

Thank you!

**Comment by odagayev** [comment]
AH!

Thank you - did not think to look there.

**Comment by odagayev** [comment]
One quick follow-up question - is there a way to get a unified bed file? I would love to just look at all of the differentially expressed motifs for a specific chromosome region across ALL of the considered motifs.

**Comment by msbentsen** [comment]
> One quick follow-up question - is there a way to get a unified bed file? 

Not directly from TOBIAS, but if you write together all the `_overview.txt`-files, e.g. at:
`<BINDETECT_OUTPUT>/<TF>/<TF>_*_overview.txt`

For example, if the folder is called TFBS, using:
`$ tail -n +2 -q TFBS/*/*_overview.txt > merged.bed` (tail is used to remove the header of the file)

Then, you can subset and sort the sites based on the log2fcs (in the last column). That should give a nice overview of the most differentially changed TF sites overall!

**Comment by odagayev** [comment]
Perfect - thanks again!
