### ISSUE TITLE
Difference between bound and unbound

### ISSUE THREAD

**Issue by Danvor** [loosolab/TOBIAS#141]
Hi, 

I am trying to find how the bound vs unbound is calculated but cannot find it. Could you point me to it?
Also does it mean that the bound files have the TFs bound to those motif locations, while unbound have the motifs but no TF is "sitting" at that region?

How should one go about setting the cut off for bound vs unbound?

Thanks.

Dan

**Comment by msbentsen** [comment]
Hi,

Ah yes sorry, it is a bit hidden in the supplementary information of the TOBIAS paper ([here](https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-020-18035-1/MediaObjects/41467_2020_18035_MOESM1_ESM.pdf)). It reads:
> In the second step of the algorithm, every TF binding site found (for each motif given as input) is split into
bound and unbound sites based on a score threshold per condition. The threshold is set at the level of
significance of a normal-distribution fit to the background distribution of scores (user-defined p-value).

Which means that the threshold is estimated based on a fit to the distribution of counts (which is normalized across all conditions). For example:
![image](https://user-images.githubusercontent.com/47495444/170818414-7a7eda9b-48b1-46ec-be85-388aebcf8a25.png)

The option `--bound-pvalue` can be used to adjust how strict the threshold is.

Indeed, the sites "unbound" means that a motif was found, but there was not enough evidence from the ATAC-seq counts to say that the TF was bound there. I think the default threshold generally works well, but if you want, you can also (manually, not part of TOBIAS) read the individual scores from the `<outdir>/<TF>/beds/<TF>_bound.bed`-bound files and set a threshold specific for each TF. I would go for a score which clearly distinguishes the background (no footprint) and bound sites (footprint), when looking at aggregate plots. I hope this is helpful.

BR Mette

**Comment by adelosan521** [comment]
"Indeed, the sites "unbound" means that a motif was found, but there was not enough evidence from the ATAC-seq counts to say that the TF was bound there. "

If I am doing a single-condition analysis, how do I interpret bound versus unbound?\

Niko
