### ISSUE TITLE
ATACorrect ignoring chromosome names with M letter

### ISSUE THREAD

**Issue by gunnarschulze** [loosolab/TOBIAS#142]
Hi,

I noticed that ATACorrect was consistently dropping some of my chromosomes from the regions list and found it is  due to the hard-coded removal of all chromosomes whose name contains an "M":

https://github.com/loosolab/TOBIAS/blob/df1c72f9c0546fa65369e92b9534ed5bb9d885a6/tobias/tools/atacorrect.py#L178
and 
https://github.com/loosolab/TOBIAS/blob/df1c72f9c0546fa65369e92b9534ed5bb9d885a6/tobias/tools/atacorrect.py#L179 

I understand the intention is to drop mitochondrial chromosomes which will bias the statistics (?), but in my case it also dropped other chromosomes that happened to contain an M-letter which was confusing to me.
It is probably a rare case and I managed to fix it in my local copy, but might still be worth pointing out for other users.

Otherwise, thanks for providing such a nice tool! :)

**Comment by msbentsen** [comment]
Hi,

Thank you for pointing this out! The intention is indeed to drop the mitochondrial chromosome, as this is often highly enriched in ATAC-seq and will influence the bias calculation. But removing all chromosomes with "M" is definitely not a nice solution - I guess I have been quite biased towards common mammalian genomes :)

I made a small fix on the development branch of TOBIAS, which adds the option `--drop-chroms` as a custom list to ATACorrect, so you can fetch that as well if you want to. I like to collect a few fixes before releasing the version, but you can install directly from `pip install git+https://github.com/loosolab/TOBIAS@dev`. Running `TOBIAS --version` should confirm the version to be 0.14.0-b. 

I hope this is helpful for you or anyone else experiencing the same issue!

**Comment by gunnarschulze** [comment]
Awesome, thanks a lot! :)
