### ISSUE TITLE
BINDetect: chromsome from region "chr*"not found. 

### ISSUE THREAD

**Issue by annrosebright** [loosolab/TOBIAS#143]
Hi,

I have the following error (screenshot attached) when I am running BINDetect. I realize that the issue is coming because specific peaks are not in the genome file. I am not able to understand how that's possible? And is there a way in which the program could continue to run even if some regions are not present?  If not how could i sove this issue 

Please let me know if I need to provide any more information. 
I have also tried using different reference genomes and I get the same error, just the region/peak changes.

<img width="1207" alt="Screenshot 2022-05-30 at 15 35 56" src="https://user-images.githubusercontent.com/13627744/171004712-58f74d9f-d9a2-4291-b7e0-cce1566436ab.png">

Best,
Ann

**Comment by msbentsen** [comment]
Hi Ann,

It looks your peaks have the "chr"-prefix e.g. "chr1" instead of just "1". Did you use different fasta files for mapping and for TOBIAS? Or do the peaks come from another source? You can also check the header of the original .bam-file (used to calculate the corrected signal and footprinting .bws) to see what format the chromosomes are in, and make sure this is consistent across the input files. 

These have to match in order to fetch the signals correctly, but you can of course remove any unwanted regions from `--peaks` prior to the run.

**Comment by annrosebright** [comment]
Hi

Thank you very much. I recognized that later, and that part appears to be fixed now. But now I'm having trouble with the motif file. I'm attempting to use the motif file that I downloaded using the following method:

wget data/2022/CORE/JASPAR2022 CORE non-redundant pfms jaspar.txt https://jaspar.genereg.net/download/data/2022/CORE/JASPAR2022 CORE non-redundant pfms jaspar.txt

Because the file was in text format I changed the filename to . Jaspar added a black line before each motif. Baically tried to make the formate similar to the one given in the test data. 
It works properly when I run a test run with a smaller subset of the motifs or if I use the motif. jasper (file that you provided with the test data). I get the following error when I use the main file with all the motifs. Seems like some problem with the number of motifs it is processing. Could you please help me solve this?  Thanks in advance.

**Command:** 
TOBIAS BINDetect --motifs ../../../../genome/JASPAR2022_CORE_non-redundant_pfms_jaspar2.jaspar  --signals C7_E12_footprints.bw C5_E16_footprints.bw --genome /datastore_share/Users/ann/genome/GRCm38.p6.genome.fa  --peaks C7_C5_annotated.bed --peak_header C7_C5_annotated_header.txt --outdir BINDetect_output_2 --cond_names C7 C5 --cores 8

Error opening file /datastore_share/Users/ann/Papers/Manuscript_1/dataframe/footprint/BINDetect_output_2/bHLH77_MA1362.1/beds/bHLH77_MA1362.1.tmp in file_writer. Exception was: '[Errno 24] Too many open files: '/datastore_share/Users/ann/Papers/Manuscript_1/dataframe/footprint/BINDetect_output_2/bHLH77_MA1362.1/beds/bHLH77_MA1362.1.tmp''

**Motif file:**

>MA0004.1	Arnt
A  [     4     19      0      0      0      0 ]
C  [    16      0     20      0      0      0 ]
G  [     0      1      0     20      0     20 ]
T  [     0      0      0      0     20      0 ]

>MA0006.1	Ahr::Arnt
A  [     3      0      0      0      0      0 ]
C  [     8      0     23      0      0      0 ]
G  [     2     23      0     23      0     24 ]
T  [    11      1      1      1     24      0 ]

>MA0010.1	br
A  [     3      1      5      7      3      6      4      7      1      9      8      5      4      2 ]
C  [     1      1      2      0      0      0      1      0      8      0      0      0      0      3 ]
G  [     4      1      1      1      0      0      4      1      0      0      1      3      0      2 ]
T  [     1      6      1      1      6      3      0      1      0      0      0      1      5      2 ]

>MA0011.1	br
A  [     3      5      0      0     12      1      2      1 ]
C  [     1      2     10      1      0      1      0      2 ]
G  [     1      1      0      0      0      2      1      1 ]
T  [     7      4      2     11      0      8      9      8 ]

**Comment by annrosebright** [comment]
I thought the problem must be because there are repetitive TFS and tried adding .1 to the motif and TF. I got the following error:
Traceback (most recent call last):
  File "/home/brightann/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
  File "/home/brightann/anaconda3/lib/python3.7/site-packages/tobias/utils/utilities.py", line 98, in file_writer
  File "/home/brightann/anaconda3/lib/python3.7/site-packages/tobias/utils/utilities.py", line 95, in file_writer
OSError: [Errno 24] Too many open files: '/datastore_share/Users/ann/Papers/Manuscript_1/dataframe/footprint/BINDetect_output_2/SUT1.1_MA0400.1/beds/SUT1.1_MA0400.1.tmp'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/brightann/anaconda3/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.12.11', 'console_scripts', 'TOBIAS')())
  File "/home/brightann/anaconda3/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)
  File "/home/brightann/anaconda3/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 356, in run_bindetect
    logger.debug("Writer task return status: {0}".format([task.get() if task.ready() else "NA" for task in writer_tasks]))
  File "/home/brightann/anaconda3/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 356, in <listcomp>
    logger.debug("Writer task return status: {0}".format([task.get() if task.ready() else "NA" for task in writer_tasks]))
  File "/home/brightann/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
OSError: [Errno 24] Too many open files: '/datastore_share/Users/ann/Papers/Manuscript_1/dataframe/footprint/BINDetect_output_2/SUT1.1_MA0400.1/beds/SUT1.1_MA0400.1.tmp'
2022-06-02 18:15:37 (25173) [ERROR]     Multiprocessing logger lost connection to queue - probably due to an error raised from a child process.

**Comment by msbentsen** [comment]
Hi Ann, 

Sorry for the late reply. This has nothing to do with the motif format but rather the amount of motifs. BINDetect needs to open individual files for the motifs to write, and this often exceeds the system file limit. See also the FAQ entry here: https://github.com/loosolab/TOBIAS/wiki/FAQ#5-i-get-an-error-stating-too-many-files-open---what-do-i-do 

Can you try to set `ulimit -n 3000`? That should solve the issue.
