### ISSUE TITLE
Significance on the BIND_DETECT HTML output

### ISSUE THREAD

**Issue by odagayev** [loosolab/TOBIAS#144]
Hi!

What are the criteria that are sued to mark something "significant" on the HTML Binddetect document?

Thank you.

**Comment by msbentsen** [comment]
Hi,

The threshold is set according to the data, and it is always on the criteria: -log10(p-value) above the 95% quantile and/or differential binding scores smaller/larger than the 5% and 95% quantiles (top 5% in each direction).

So BINDetect will always highlight the top changed TFs in either direction.

**Comment by odagayev** [comment]
Thank you!
