### ISSUE TITLE
Differential binding for genotype-treatment interaction

### ISSUE THREAD

**Issue by ikumar2000** [loosolab/TOBIAS#147]
Is it possible to run a genotype-treatment interaction type analysis for differential binding? Or, any intermediate data from Tobias pipeline that could be used for such analysis?

**Comment by msbentsen** [comment]
Hi,

Can you provide a little more information what is meant by "genotype-treatment interaction type analysis"? I am not familiar with the setup of the analysis.

If you have different conditions, e.g. control, treatment1, treatment2 etc., you can compare these pairwise using `TOBIAS BINDetect` - but that would generally be in the same genotype.
