### ISSUE TITLE
DNase-seq

### ISSUE THREAD

**Issue by huangyingzhang** [loosolab/TOBIAS#148]
Is the "TOBIAS ATACorrect" suitable for DNase-seq where DNase I cut the chromatin?

**Comment by msbentsen** [comment]
Hi,

Good question - I have not used it for DNase-seq myself, but theoretically, yes! You might want to adjust the parameters of ATACorrect to `--read-shift 0 0` and `--k_flank 6`, as the DNase bias motif is not shifted and is smaller than the one for Tn5. 

I would be interested to hear your experience, if you end up using it. Please let me know :-)
