### ISSUE TITLE
Is TOBIAS pipeline supporting organisms other than mice and human?

### ISSUE THREAD

**Issue by BrianHCChan** [loosolab/TOBIAS#151]
Hi,
Thank you for the tool and I know this is not an insightful question.. However, when I am reading into the configuration file of the sample TOBIAS pipeline, I can see that the first line requires me to specify the model organism that I am using. However, the description seems like it's limited to either mice or human. I want to ask if it's possible to use other organisms (e.g. zebrafish or chicken) for the pipeline? If so, what should I be specifying on that line?

**Comment by msbentsen** [comment]
Hi Brian, 

Good question - this is poorly documented in the pipeline. Indeed, the pipeline currently only supports mouse/human/zebrafish as defaults. However, the organism is only used to set the correct genome size for MACS2 peak-calling, as a `--gsize` parameter is needed for the correct background:
https://github.molgen.mpg.de/loosolab/TOBIAS_snakemake/blob/13f05faf174e1cc8cdc5bc0171d3bbe9a87e73c4/snakefiles/preprocessing.snake#L98-L101

So another option is also to let the organism be "human", but then give the effective genome size via the configuration file, e.g:
```
macs: "--nomodel --shift -100 --extsize 200 --broad --gsize 1000000"
```
(https://github.molgen.mpg.de/loosolab/TOBIAS_snakemake/blob/ff6cdf2b1429966ecf9b761e4427078d2680219d/example_config.yaml#L31)

This will overwrite any `--gsize` set by organism, and use the gsize given in the configuration file. Hope this "hack" works for you!
