### ISSUE TITLE
issue with "TOBIAS CreateNetwork"

### ISSUE THREAD

**Issue by lynnyummy** [loosolab/TOBIAS#154]
Hi, I am trying to apply `TOBIAS CreateNetwork` to reconstruct a TF-TF network. All the profiles I got looks normal, however it just reported the error of `ValueError: The column label 'Origin_0' is not unique` when running the `CreateNetwork `. Could you please help to take a look at it? Thank you very much!

my command is `TOBIAS CreateNetwork --TFBS /02-Tobias/network/x_tfbs/x_stage_1/*.bound.bed --origin x_gene2TF.txt  --outdir x_network_1`
error
`Traceback (most recent call last):
  File "/data/home/user/.conda/envs/biotools/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.12.0', 'console_scripts', 'TOBIAS')())
  File "/data/home/user/.conda/envs/biotools/lib/python3.6/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)             
  File "/data/home/user/.conda/envs/biotools/lib/python3.6/site-packages/tobias/tools/create_network.py", line 163, in run_network
    sites_table_convert = sites_table.merge(origin_table[[source_col_origin, target_col_origin]], left_on=target_col_tfbs, right_on=target_col_origin, how="inner")
  File "/data/home/user/.conda/envs/biotools/lib/python3.6/site-packages/pandas/core/frame.py", line 7297, in merge
    validate=validate,
  File "/data/home/user/.conda/envs/biotools/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 86, in merge
    validate=validate,
  File "/data/home/user/.conda/envs/biotools/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 627, in __init__
    ) = self._get_merge_keys()
  File "/data/home/user/.conda/envs/biotools/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 983, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/data/home/user/.conda/envs/biotools/lib/python3.6/site-packages/pandas/core/generic.py", line 1710, in _get_label_or_level_values
    f"The {label_axis_name} label '{key}' "
ValueError: The column label 'Origin_0' is not unique.`

Thank you very much for your helps!

**Comment by lynnyummy** [comment]
> Hi @lynnyummy,
> 
> Could you provide me with the full log-output of `TOBIAS CreateNetwork`? That will help me to see what happened in the steps before the error. Thank you!

Hi @msbentsen ,Thank you so much for the quick reply! And so sorry for my late response, the following are my log-output when do the network reconstruction,
`Variable OMP_NUM_THREADS has been set to 2
# TOBIAS 0.12.0 CreateNetwork (run started 2022-07-10 21:59:21.952799)
# Working directory: /data/scratch/user/00-ATAC/22-Comparison_Species_Ctel/02-Tobias/network/Species_tfbs
# Command line call: TOBIAS CreateNetwork --TFBS /data/scratch/user/00-ATAC/22-Comparison_Species_Ctel/02-Tobias/network/Species_tfbs/Species_stage_1/Average_203_sort_Species_merged_1_footprints_bound.bed /data/scratch/user/00-ATAC/22-Comparison_Species_Ctel/02-Tobias/network/Species_tfbs/Species_stage_1/Average_583_sort_Species_merged_1_footprints_bound.bed /data/scratch/user/00-ATAC/22-Comparison_Species_Ctel/02-Tobias/network/Species_tfbs/Species_stage_1/Average_587_sort_Species_merged_1_footprints_bound.bed /data/scratch/user/00-ATAC/22-Comparison_Species_Ctel/02-Tobias/network/Species_tfbs/Species_stage_1/Average_594_sort_Species_merged_1_footprints_bound.bed /data/scratch/user/00-ATAC/22-Comparison_Species_Ctel/02-Tobias/network/Species_tfbs/Species_stage_1/motif_Species_103_sort_Species_merged_1_footprints_bound.bed /data/scratch/user/00-ATAC/22-Comparison_Species_Ctel/02-Tobias/network/Species_tfbs/Species_stage_1/Species_CVGTTWWKTCNGTTA_sort_Species_merged_1_footprints_bound.bed /data/scratch/user/00-ATAC/22-Comparison_Species_Ctel/02-Tobias/network/Species_tfbs/Species_stage_1/Species_GRTGMTRGAGCC_sort_Species_merged_1_footprints_bound.bed /data/scratch/user/00-ATAC/22-Comparison_Species_Ctel/02-Tobias/network/Species_tfbs/Species_stage_1/Species_GTGSTGCT_sort_Species_merged_1_footprints_bound.bed /data/scratch/user/00-ATAC/22-Comparison_Species_Ctel/02-Tobias/network/Species_tfbs/Species_stage_1/Species_MACCTTCYATGGCTCCCTAKTGCCY_sort_Species_merged_1_footprints_bound.bed --origin Species_gene2TF.txt --outdir Species_netword_1

2022-07-10 21:59:21 (25758) [INFO]	Reading all input binding sites
2022-07-10 21:59:22 (25758) [INFO]	- Total of 17274 sites found

2022-07-10 21:59:22 (25758) [INFO]	Matching target genes back to TFs using --origin
2022-07-10 21:59:22 (25758) [INFO]	Subset 17274 sites to 17274 sites with any target given
2022-07-10 21:59:22 (25758) [INFO]	Subset 17274 sites to 0 sites with matching target id in '--origin'
Traceback (most recent call last):
  File "/data/home/user/.conda/envs/biotools/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.12.0', 'console_scripts', 'TOBIAS')())
  File "/data/home/user/.conda/envs/biotools/lib/python3.6/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/data/home/user/.conda/envs/biotools/lib/python3.6/site-packages/tobias/tools/create_network.py", line 163, in run_network
    sites_table_convert = sites_table.merge(origin_table[[source_col_origin, target_col_origin]], left_on=target_col_tfbs, right_on=target_col_origin, how="inner")
  File "/data/home/user/.conda/envs/biotools/lib/python3.6/site-packages/pandas/core/frame.py", line 7297, in merge
    validate=validate,
  File "/data/home/user/.conda/envs/biotools/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 86, in merge
    validate=validate,
  File "/data/home/user/.conda/envs/biotools/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 627, in __init__
    ) = self._get_merge_keys()
  File "/data/home/user/.conda/envs/biotools/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 983, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/data/home/user/.conda/envs/biotools/lib/python3.6/site-packages/pandas/core/generic.py", line 1710, in _get_label_or_level_values
    f"The {label_axis_name} label '{key}' "
ValueError: The column label 'Origin_0' is not unique.`

I am thinking probably could be my bound bed files don't have the gene name information?

Thank you very much!

All the best!

**Comment by msbentsen** [comment]
Hi, 

Yes it looks like your input .bed-files to not contain a column matching to the `--origin` file. But I agree the error message is not helping - I will have a look at creating a better check for this.

How did you annotate the input TFBS? Maybe this will help to check whether the gene names were correctly added.

**Comment by lynnyummy** [comment]
> Hi,
> 
> Yes it looks like your input .bed-files to not contain a column matching to the `--origin` file. But I agree the error message is not helping - I will have a look at creating a better check for this.
> 
> How did you annotate the input TFBS? Maybe this will help to check whether the gene names were correctly added.

Hi, Thank you so much for your reply! The following are my input for network reconstruction, the Gene2TF file and the bound.bed. I was thinking the bed is the issue, since we don not have a well custom genome annotation...

Gene2TF `,Average_203` is the TF, and `ABC23196.1 ` is the Gene.
`Average_203	ABC23196.1`.

Bound.bed
`Scaffold01	890532	890542	Average_203	8.1794	+	Scaffold01	890089	891413	ABC_peak_89	7.11899`

Are they suitable for annotation?

Thank you very much!

**Comment by msbentsen** [comment]
Hi @lynnyummy ,

Did you annotate the `bound.bed` regions to genes before running `CreateNetwork`?

I would expect that the bound.bed should contain more columns including the annotated gene name like:
`Scaffold01 890532 890542 Average_203 8.1794 + Scaffold01 890089 891413 ABC_peak_89 7.11899  gene1`

I can recommend you use the TOBIAS Snakemake pipeline, as it already does the annotation internally with UROPA when you give a gtf file. Link is here: https://github.molgen.mpg.de/loosolab/TOBIAS_snakemake

**Comment by lynnyummy** [comment]
> Hi @lynnyummy ,
> 
> Did you annotate the `bound.bed` regions to genes before running `CreateNetwork`?
> 
> I would expect that the bound.bed should contain more columns including the annotated gene name like: `Scaffold01 890532 890542 Average_203 8.1794 + Scaffold01 890089 891413 ABC_peak_89 7.11899 gene1`
> 
> I can recommend you use the TOBIAS Snakemake pipeline, as it already does the annotation internally with UROPA when you give a gtf file. Link is here: https://github.molgen.mpg.de/loosolab/TOBIAS_snakemake

Hi @msbentsen, Thanks for your reply! Yeah my case is the bed is not annotated.. I think I can give the snake make a try!

Does the `gene1` need to be a specific gene name e.g. `GAPDH` or it could be a gene id from my gtf `ABC_gene_1`?

Thank you very much!

**Comment by msbentsen** [comment]
> Does the gene1 need to be a specific gene name e.g. GAPDH or it could be a gene id from my gtf ABC_gene_1?

The `gene1` column just has to match the gene names/id given in the `Gene2TF.txt` - so it can also be your own gene names.

**Comment by lynnyummy** [comment]
> > Does the gene1 need to be a specific gene name e.g. GAPDH or it could be a gene id from my gtf ABC_gene_1?
> 
> The `gene1` column just has to match the gene names/id given in the `Gene2TF.txt` - so it can also be your own gene names.

sure! I got the idea now!

Thanks you very much @msbentsen!
