### ISSUE TITLE
Error with TOBIAS PlotTrack

### ISSUE THREAD

**Issue by loganminhdang** [loosolab/TOBIAS#159]
Hi, per your request, I'm creating a separate issue thread. Thanks in advance for your time! 

I received the following error while using TOBIAS Plottrack. 

Traceback (most recent call last):
File "/path/to/bin/TOBIAS", line 11, in
load_entry_point('tobias==0.13.3', 'console_scripts', 'TOBIAS')()
File "/path/to/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
args.func(args)
File "/path/to/lib/python3.7/site-packages/tobias/tools/plot_tracks.py", line 279, in run_tracks
sites_in_region = pb_sites.intersect(pb_region, u=True).sort().saveas(os.path.join(f_prefix, "sites.bed"))
File "/path/to/lib/python3.7/site-packages/pybedtools/bedtool.py", line 923, in decorated
result = method(self, *args, **kwargs)
File "/path/to/lib/python3.7/site-packages/pybedtools/bedtool.py", line 407, in wrapped
decode_output=decode_output,
File "/path/to/lib/python3.7/site-packages/pybedtools/helpers.py", line 460, in call_bedtools
raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError:
Command was:

    bedtools sort -i /tmp/73934680.1.short.qc/pybedtools.jefni8x1.tmp
Error message was:
terminate called after throwing an instance of 'std::invalid_argument'
what(): stoll

This is when I'm trying to use TOBIAS PlotTracks. I have been using the tool without any issues until recently when this error started showing up. I have tried many ways but haven't been successful in getting it to work. I reckon it could be due to my input; however, since the inputs were direct outputs of previous instances of TOBIAS, I am unsure as to why this error occurred. Would greatly appreciate any guidance.

**Comment by msbentsen** [comment]
Hi, 

Thank you for creating the issue! Is this error happening on all data or just some?

Could you for example try to run it on the test data (description [here](https://github.com/loosolab/TOBIAS/wiki/test-data)) and run the example command given on the wiki [here](https://github.com/loosolab/TOBIAS/wiki/PlotTracks)?

That would help us to see whether it is an installation error or a data error. Thank you!

**Comment by loganminhdang** [comment]
The tool worked on some of my data, so I'm quite certain it's a data error, which probably makes it hard for you to diagnose. I'm just trying to probe if you have seen this error before. Otherwise, I can rerun all of my previous analyses to generate new data as input for the tool.

**Comment by msbentsen** [comment]
I have not seen this particular error before, no.... so if you are able to reproduce it with a small dataset and send it to me, that would be a big help.

However, I just found this issue on the bedtools page: https://github.com/arq5x/bedtools2/issues/917. Does your input data have 12 columns? Maybe it is a similar issue of bedtools assuming your data is BED12.

**Comment by loganminhdang** [comment]
It works, thank you so much. Some of my bed files indeed had 12 columns. Your support was wonderful.

**Comment by msbentsen** [comment]
That is great, thank you for the update! I will close the issue, but hopefully this should also serve as reference to help anyone in the future encountering the same issue.
