### ISSUE TITLE
Reverse Strand Issue with BAM from BedToBam

### ISSUE THREAD

**Issue by suragnair** [loosolab/TOBIAS#16]
I started with aligned reads in a 6 column BED format (ENCODE tagAlign) and converted it to a BAM using `bedtools bedtobam`. The resulting BAM does not have sequence in it. As a result, the `read.query_length` is set to 0. This messes up the cutsite calculation for the reverse strand here:

https://github.com/loosolab/TOBIAS/blob/88393705ddb76b81003156a0bd76e2a8831e049d/tobias/utils/ngs.pyx#L98

Since `self.query_length` is 0. It ends up using the + coordinate of the reverse strand reads which basically ends up in a meaningless computation. 

From pysam ([link](https://github.com/pysam-developers/pysam/blob/74fa4ef2e21e0a02e2165e934d214eb772cf5bb6/pysam/libcalignedsegment.pyx#L1355-L1362)):
```
        The length of a query is 0 if there is no
        sequence in the BAM/SAM file. In those cases, the read length
        can be inferred from the CIGAR alignment, see
        :meth:`pysam.AlignedSegment.infer_query_length
```

A simple fix would be to change
https://github.com/loosolab/TOBIAS/blob/88393705ddb76b81003156a0bd76e2a8831e049d/tobias/utils/ngs.pyx#L84

to 
```
self.query_length = read.query_length if read.query_length>0 else read.infer_query_length()
```
Or alternatively support aligned read BED files as inputs. This is relevant since for single-cell analyses, workflows usually consist of working with fragment/read BED files with barcode attached.

**Comment by msbentsen** [comment]
Oh, I was not aware of this difference in query_length for bam/bedtobam input. Thank you so much for your fix - it is perfect! I added this to TOBIAS 0.11.2, which is on PyPI now, and will probably update on bioconda some time today. Hope it helps you out!
