### ISSUE TITLE
TF's below footprint threshold are in bound bedfile and TF's that shouldn't be in unbound file are in there?

### ISSUE THREAD

**Issue by nessj216** [loosolab/TOBIAS#161]
Hello,
I understand that found motifs that have a p-value smaller than threshold p-value make it to the TF list, where they are assigned their footprint score. (TF motifs with too high a p-value never get a footprint score, right?). Then TF motifs that have a high enough footprint score make it the bound.bed file, while the TF motifs that have a footprint score below the threshold are in the unbound.bed file.
BUT I have found a potential issue if my understanding above is correct. I am getting too low of footprint scores in my bound.bed file (that fall below the threshold value established). Conversely, I am getting motifs with high 
enough footprint scores that remain in the unbound bed file. For example here you can see the 'bound', 'unbound' and 'all' bed files in IGV, where the footprint threshold from Tobias (for this particular ATAC replicate) is calculated to be ~3.5. BUT all the motifs--even though they their scores is above that threshold--are still on the unbound list. 

<img width="1150" alt="Screen Shot 2022-07-30 at 3 12 30 PM" src="https://user-images.githubusercontent.com/100496937/181945357-7f6390f7-4199-473c-8947-8efaea5e0c89.png">

(P.S. I am NOT doing differential analysis of TF footprints between two conditions. I am only doing one condition. The input to BINDetect is 1)the footprint file made from ScoreBigwig, 2)the SAME peak bed file I used in all the other steps!, 3) my PWM file, 4) the genome file (drosophila in this case). 

any help would be greatly appreciated!!!! thank you

**Comment by nessj216** [comment]
maybe the scores aren't in a large enough peaks?

**Comment by nessj216** [comment]
here is the converse--where TFs with too low footprints are in the bound file 
<img width="1137" alt="Screen Shot 2022-08-02 at 11 17 22 AM" src="https://user-images.githubusercontent.com/100496937/182410613-c6321ae8-72a6-4a52-a90d-0b9cd7becb40.png">

**Comment by msbentsen** [comment]
Hi @nessj216 ,

The score which is shown in IGV is the **motif score** (5th column of the .bed), which is the score of the TF motif to the genome sequence - and this is independent of footprinting. The **footprint score** is found in the column named `<condition>_score` in the bindetect_output txt-file. There is also an overview of the output columns [here](https://github.com/loosolab/TOBIAS/wiki/BINDetect#output). I hope this clears up your question!

BR Mette

**Comment by nessj216** [comment]
thank you a million!! sorry about that!! this is very helpful
