### ISSUE TITLE
I am not sure how can I get the `.bed` file for  `TOBIAS ATACorrect -p`

### ISSUE THREAD

**Issue by danli349** [loosolab/TOBIAS#165]
Hello,

I am not sure how can I get the `.bed` file for 
`TOBIAS ATACorrect -p`
Should I use a peak file of a single sample or should I merge all of the `narrowPeak` files of `macs2` output using `mergePeaks`?
```
mergePeaks -d given -code -matrix Merge \
-venn Venn \
*.narrowPeak> Homer_Merged.bed
```

Thanks

**Comment by msbentsen** [comment]
Hi @danli349,

Thank you for your question. The answer is yes to the second option - you should merge all of the narrowPeaks for all samples you are running with TOBIAS. This is also described in more detail [here](https://github.com/loosolab/TOBIAS/wiki/FAQ#3-what-peak-file-should-i-use-as-input). 

Hope that helps!
