### ISSUE TITLE
Normalizing footprint scores per TF for a single condition 

### ISSUE THREAD

**Issue by nessj216** [loosolab/TOBIAS#169]
Hello,
thanks for the awesome tool!
I am interested in comparing the footprint score profiles of TFBSs between several different enhancers . So I am averaging the footprint scores per TF per enhancer to estimate TFBS enrichment. BUT-- I ran BinDetect separate for EACH TF (I wrote code to automate this.... I used different motif p-values for each TF--so I needed to run BinDetect separate for each). I am not running comparative analysis between conditions, just running BINDetect on a single atac condition. 

Sorry if this is obvious: I am trying to figure out if the footprint scores are normalized if we are running analysis for a single condition (how I want to normalize: subtract mean, divide by standard deviation of  _bound_ TF footprint scores in the genome). 

Best,
Jillian

**Comment by msbentsen** [comment]
Hi Jillian,

This is a very valid question. The answer is that no, there is no normalization for single-input runs. Even for multi-conditions, the footprints are never normalized within each condition, only across conditions to be comparable globally. So if you want to directly compare scores of say TF1 and TF2, then your Z-score approach seems good.

Best Mette

**Comment by nessj216** [comment]
thanks a million! (and you definitely summarized my overly detailed question well! 😄)
