### ISSUE TITLE
restarting does not continue from where it left

### ISSUE THREAD

**Issue by gianfilippo** [loosolab/TOBIAS#170]
Hi,

is there a way to rerun the pipeline, continuing from where it left, rather than from the beginning ?

Thanks

**Comment by msbentsen** [comment]
Hi Gianflippo,
Can you provide a little bit more information on this? If nothing changed in the input files, and you are running with the snakemake command given in the documentation, then it will start where it left off. So I need a little more info to know why it didn't do that in your case, thanks!

**Comment by gianfilippo** [comment]
Hi,

you are right, I definitely did not provide enough info.

Meanwhile, I identified the issue and, of course, it was my mistake. I forgot to change the command line to avoid rerunning from start!!

Thanks for your prompt reply
