### ISSUE TITLE
Inquiry of the statistics test for the TOBIAS BINDetect

### ISSUE THREAD

**Issue by lynnyummy** [loosolab/TOBIAS#171]
Hi,

I used TOBIAS in my analyses, and now the journal requires us to provide the statistics test of  a package of TOBIAS, I checked with `TOBIAS BINDetect -h`, and it only shows that `--bound-pvalue  <float>           Set p-value threshold for bound/unbound split (default:0.001)`
I need to provide what statistics test used here for the p-values?

Thank you very much!

**Comment by msbentsen** [comment]
Hi @lynnyummy 

The background model of all footprint scores is determined using a gaussian mixture model as seen below:
![image](https://user-images.githubusercontent.com/47495444/203033981-1f3e9bda-6897-4e94-9c2d-e86fbe3be826.png)

The p-value is then calculated in python using `scipy.stats.norm.ppf(1-pvalue)` with the parameter of the right-most distribution (in this case component 1), as component 2 is the 0-component.

Probably you can summarize this as:

> TOBIAS estimates a threshold between unbound/bound binding sites by first fitting a two-component gaussian-mixture model to the log-transformed background distribution of scores, and next, estimating the significance threshold of the right-most normal distribution (by a user-defined p-value)

Hope this will be enough for the journal.

BR Mette

**Comment by lynnyummy** [comment]
> Hi @lynnyummy
> 
> The background model of all footprint scores is determined using a gaussian mixture model as seen below: ![image](https://user-images.githubusercontent.com/47495444/203033981-1f3e9bda-6897-4e94-9c2d-e86fbe3be826.png)
> 
> The p-value is then calculated in python using `scipy.stats.norm.ppf(1-pvalue)` with the parameter of the right-most distribution (in this case component 1), as component 2 is the 0-component.
> 
> Probably you can summarize this as:
> 
> > TOBIAS estimates a threshold between unbound/bound binding sites by first fitting a two-component gaussian-mixture model to the log-transformed background distribution of scores, and next, estimating the significance threshold of the right-most normal distribution (by a user-defined p-value)
> 
> Hope this will be enough for the journal.
> 
> BR Mette

Hi @msbentsen,

Thank you very much for this very detailed explanation! It helps me a lot! Many thanks!

Since the significance threshold is estimated from the right-most normal distribution, can I provide that it is one-tail test?
