### ISSUE TITLE
Use pre-calculated Tn5 bias?

### ISSUE THREAD

**Issue by maxdudek** [loosolab/TOBIAS#174]
Hi, 

I have ~200 ATACseq samples which are genotyped across thousands of SNP variants.

For each variant, I would like to run TOBIAS separately on 3 bam files joined by genotype (aa, Aa, AA) to test how footprint score at the variant locus changes with genotype.

The issue with this approach is that TOBIAS will calculate the Tn5 bias separately for each run, which will be extremely inefficient and time-consuming, as I will be using the same samples each time. 

Is there a way to input a pre-calculated bias matrix (from a previous run) into ATACorrect that would prevent this step from being repeated? If not, I would love if this feature could be added.

Thanks!

**Comment by msbentsen** [comment]
Hi,

Thank you for your issue, this is a great idea! ATACorrect already outputs a .pkl file (`<name>_AtacBias.pickle`) contaning the estimated Tn5 bias object, so I just added the parameter `--bias-pkl` to ATACorrect in `TOBIAS 0.15.0` to be able to read this in during the run.

You will still need to run ATACorrect once, but after that you can use the already calculated bias object in other runs, like so:
```
$ TOBIAS ATACorrect --bam test_data/Bcell.bam --genome test_data/genome.fa.gz --peaks test_data/merged_peaks.bed --blacklist test_data/blacklist.bed --outdir ATACorrect_output --cores 8
$ TOBIAS ATACorrect --bam test_data/Tcell.bam --genome test_data/genome.fa.gz --peaks test_data/merged_peaks.bed --blacklist test_data/blacklist.bed --outdir ATACorrect_output_prebias --cores 8 --bias-pkl ATACorrect_output/Bcell_AtacBias.pickle
```

One thing I will say is that you have to be careful about doing this with samples which are very different, as the bias is specifically calculated in terms of background GC-content etc. - but for your application, it should be just fine. 

So please fetch the new version to get this feature. I hope it helps you out!

**Comment by maxdudek** [comment]
Thank you so much, works like a charm!

**Comment by maxdudek** [comment]
@msbentsen One more minor comment on this: ideally running ATACorrect with `--bias-pkl` should not output a new `_AtacBias.pickle` file, or else several duplicate files will be made.
