### ISSUE TITLE
Tools are not running with TOBIAS <Toolname> command

### ISSUE THREAD

**Issue by eziotfok** [loosolab/TOBIAS#183]
Hi,

I am very new to this and this is probably a user issue, but I would like to get some help if possible. I am trying to run TOBIAS on a server and I have managed to install it using the TOBIAS_ENV method. Everything seems to have gone well, and I can type in TOBIAS <Toolname> to bring up a menu of options and helpful instructions. However, when I attempt to run the command with all the necessary input files, I am getting a "command not found" response. Any help on this would be great. Thanks!

**Comment by msbentsen** [comment]
Hi, thanks for your issue - can you give me a little more information, e.g.:
- Exactly what command are you trying to use?
- What version of TOBIAS are you using (`TOBIAS --version`)
- Maybe show a screenshot?
