### ISSUE TITLE
BINDetect output question

### ISSUE THREAD

**Issue by adelosan521** [loosolab/TOBIAS#186]
Hi,

I had a simple question. What is the last column in the output bed files from BINDetect? I am attaching a snapshot below. It is in the P column. Also, just to double-check, the E column is footprint score?

![image](https://user-images.githubusercontent.com/72091611/215577095-902a006b-91be-4d24-80c2-606d5f9e4188.png)

**Comment by msbentsen** [comment]
Hi, please have a look at the output file specification here: https://github.com/loosolab/TOBIAS/wiki/BINDetect#output
