### ISSUE TITLE
annotating peak regions for BINDetect 

### ISSUE THREAD

**Issue by PriyaLakr** [loosolab/TOBIAS#189]
Hi,

I'm using a unannotated peak file for correction and footprint step. Now, I need to do differential BINDetect, for that should I use the same peak file or annotation is mandatory for BINDetect step. And annotation, can we use any other existing tools like homer, or uropa (used in the snakemake workflow)? 

Thank you,

**Comment by msbentsen** [comment]
Hi,

You can use any peak file for BINDetect - it does not need to be annotated. The thing you gain by annotation is that the columns from the input peaks are brought into the output TFBS, which makes it easier to associate TFs to genes afterwards. But you can perform the annotation with any tool you like, as long as the peaks file contains the same coordinates as used in the correction and footprint steps. Hope that explains the usage!

BR Mette

**Comment by PriyaLakr** [comment]
Thanks Mette.
