### ISSUE TITLE
Is it possible to get the list of the TFBS around a gene and its score?

### ISSUE THREAD

**Issue by smallfade** [loosolab/TOBIAS#19]
I'm trying to get all the TFBS around each gene of each condition, but got confused by the outputs from BINDetect. 

In outdir/TFBS/TF_overview.{txt,xlsx}, there are TFBS_score, cond_score, what is these two scores? I guess cond_score is the footprinting depth of a TFBS in a condition, then what is TFBS_score? What does the peak_id mean in this file?

In outdir/overview/all_cond_bound.bed, what are the fifth and the last columns?

Thanks!

**Comment by msbentsen** [comment]
Hi, you are correct that the `cond_score` is the footprint score of the TFBS for this condition (and is also named after each conditon). The `TFBS_score` is the score of the motif match to the underlying sequence, and is therefore independent of the footprinting. The higher the score, the better the sequence matched to the input motif.

`Peak_id` is the id/name of the input peak given in  `--peaks`.

For the `outdir/overview/all_<cond>_bound.bed`-files, the 5th column is again the `TFBS_score` and the last column is the footprint score for this condition, e.g. `<cond>_score`.

**Comment by odagayev** [comment]
Hi!

For the TFBS_score in the overview .txt file - what is considered a "high score" vs. a "low score"? For example, for an ATAC experiment I ran, I got a score of 7.3623 for column 5. 

Conversely, for some "condition scores" I got a .76 and a 2.04 on the same motif - can you elaborate what some context for those numbers vs. the overall motif score? 

Thank you so much for taking the time to answer these questions!

**Comment by msbentsen** [comment]
Hi, 

**Column 5** is the score of the motif to the DNA, so those scores tell you the raw match to the genome (not related to footprinting). The scores are also independent for each motif, so a score of 7.3 for one motif is not comparable to 7.3 for another motif. The minimum score allowed is controlled by the `--motif-pvalue` parameter, so even a "low score" is actually a score above the match threshold. I usually don't look at these and just accept that "this is a motif hit".

**Condition scores** are not related to the motif score - only to the footprinting data. These are normalized globally, so a motif with scores of 0.76 and 2.04 would indicate a change between the two conditions. Some motifs naturally show stronger footprints (even if they are not changed between conditions), so smaller "condition scores" do not necessarily mean less important. To take this effect into account, the differential binding score is calculated, and these are comparable across all TFs.

I hope this makes sense for your question!
