### ISSUE TITLE
Interesting pattern in FP score distribution

### ISSUE THREAD

**Issue by maxdudek** [loosolab/TOBIAS#190]
Hi,

I have been using TOBIAS as part of my research project, and it's been a great tool. 

I ran TOBIAS ATACorrect and ScoreBigwig on about 50 or so bam files, and plotted the FP score distribution (at a random-ish subset of sites) for each sample:

![image](https://user-images.githubusercontent.com/36005725/217656014-ad30f0b3-4616-4a41-a038-b8d9eb2a72aa.png)

I'm very curious about the tri-modal pattern that appears in most of these samples, and wonder if you can think of any explanation for it. The peaks occur below the binding threshold, so I'm not concerned about this affecting important results, but it would be nice to know what's happening.

We've tried to separate these sites by:
- Length and read depth of the ATAC-seq peaks they belong to
- The footprint and background widths that TOBIAS selects when calculating FP score (w<sub>b</sub> and w<sub>f</sub>).
in order to determine if they are associated with the different distribution peaks.

If you have any thoughts on why this happens, it would be greatly appreciated!

**Comment by maxdudek** [comment]
Ahh thank you that's very helpful! I did not use the snakemake pipeline, but I **_have_** been using the same peak file for all samples, which is a merge of all of the bams. Makes sense! I may want to rerun with sample-specific input peaks and see what happens then.

**Comment by msbentsen** [comment]
In general, you want to use .bed-files with all peaks in them, as this enables finding the "differential" peaks. If you only have peaks from one condition, the volcano-plots might be very skewed to one direction in the final plot. But for testing, yes it might be interesting to try it with the sample-specific input!
