### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by adelosan521** [loosolab/TOBIAS#196]
Hi,

Thanks for your help with TOBIAS. I think TOBIAS is a really great program and I am actually wrapping up work with TOBIAS now and wanted to ask if I could ask you more questions via email. Let me know if this might be possible.

**Comment by msbentsen** [comment]
Hi, I can't promise that I can help, but feel free to contact me on the email in the repository README (https://github.com/loosolab/TOBIAS#readme).
