### ISSUE TITLE
Sequencing depth / coverage 

### ISSUE THREAD

**Issue by adelosan521** [loosolab/TOBIAS#206]
Hi,

I was curious if it's known what sequencing depth / coverage is needed for TOBIAS to work well. Is this different from other TF footprinting methods? Is it different between differential motif enrichment and detection of individual TF occupancy events?

Best,

Niko

**Comment by msbentsen** [comment]
Hi,

Please have a look here for guidelines on sequencing depth: https://github.com/loosolab/TOBIAS/issues/152#issuecomment-1180662857. In general, if you need to identify individual TF occupancy events, this requires deeper sequencing than seeing an aggregate footprint (as these are collected over thousands of sites) - but this is highly individual for each dataset, so it is not possible to set a clear threshold of "number of reads" required. I don't know how this differs across different footprint methods, so this is something you will have to ask the authors of these other methods about and compare.

BR Mette
