### ISSUE TITLE
BINDetect: --peaks merged_peaks_annotated.bed

### ISSUE THREAD

**Issue by deep-buddingcoder** [loosolab/TOBIAS#208]
Hi Mette,

I want to run BINDetect with my own data file.
For this, I need to generate an annotated peak bed file, and I want it to be similar to < test_data/merged_peaks_annotated.bed > as provided in case of downloaded test_data set.

Could you please let me know, if "test_data/merged_peaks_annotated.bed" was generated from "test_data/merged_peaks.bed" using UROPA?

Thanks
Deep

**Comment by msbentsen** [comment]
Hi Deep,

Yes indeed, the annotated peaks file is the output of UROPA. More information on how the test dataset was created can be found here: https://github.com/loosolab/TOBIAS/wiki/test-data#data-processing

BR Mette

**Comment by deep-buddingcoder** [comment]
Thanks for the advice. Appreciate it. I am still working to generate annotated file using UROPA. I have some issues with using UROPA which I will discuss in UROPA git hub web page but this issue can be considered solved as of now.
