### ISSUE TITLE
Using TOBIAS without BAMs

### ISSUE THREAD

**Issue by ndejay** [loosolab/TOBIAS#209]
Hello,

Is it possible to use TOBIAS without BAM files?

Briefly, I am looking to compare footprints between two pseudo bulk replicates derived from 10X scATAC where I have Cell Ranger ATAC fragments and +4/-5 shifted bigwigs (from ArchR).

I'm curious to get your thoughts on whether this is possible.

Thanks!
Nic

**Comment by msbentsen** [comment]
Hi Nic,

Unfortunately, it is not possible to use a fragments file for TOBIAS. It is currently set up to read .bam-files as these can be read in parallel and therefore improve speed. You can use the shifted bigwigs directly into `TOBIAS Scorebigwig` if you want, but then you will lose the effect of Tn5 bias correction offered by `TOBIAS ATACorrect`.

I believe you can get .bam output from Cell Ranger as well though - I hope you find a solution!

Best Mette

**Comment by ndejay** [comment]
Thanks a lot for your help, Mette!  This is helpful.

I don't have the BAM outputs, unfortunately, only the shifted bigwigs normalized by read depth.  Would the following still work provided I reduce bin size to 1?

<img width="1563" alt="Screen Shot 2023-08-01 at 10 44 24 AM" src="https://github.com/loosolab/TOBIAS/assets/1663634/4dc39fc6-d12a-4cf4-b6cd-97927724a572">

**Comment by msbentsen** [comment]
Hi @ndejay ,

Yes technically, if every position contains 1bp-resolution pilup of 5' read positions, it will work. However, from your screenshot it looks like the bigwig represent the full read lengths (e.g. 100bp)? That would unfortunately not work as TOBIAS needs the start-position of the read to estimate the Tn5 insertion site.
