### ISSUE TITLE
Is TOBIAS capable of scanning for TFBSs without calculating binding scores?

### ISSUE THREAD

**Issue by andradejon** [loosolab/TOBIAS#214]
Part of my project relies on determining changes in TF binding between conditions, which is fine as that's the main functionality of TOBIAS. For another part, however, I'm trying to predict potential TF targets in a single sample, so I'm interested in simply the presence or absence of TFBSs within bed file regions. BinDetect scans for TFBSs naturally, but this requires the input of scores generated from earlier steps in the TOBIAS pipeline. Can TOBIAS find these binding sites without scores? If not, are there other tools that scan in the same way as TOBIAS? I'd rather not use a different tool only to find out later that the methods of TFBS detection are slightly different.

Thanks in advance! TOBIAS has been a huge help in my work.

**Comment by andradejon** [comment]
Found the solution! Just use TOBIAS TFBScan and I only need to supply the fasta file, the motifs, and my regions of interest.

**Comment by msbentsen** [comment]
Great, that would have been my suggestion too! Basically BINDetect uses the same functionality for motif scoring as TFBScan, but TFBScan just uses the genome sequence, and not footprints, to find the "raw" TFBS.
