### ISSUE TITLE
Getting footprint scores at each individual region

### ISSUE THREAD

**Issue by sebastian-gregoricchio** [loosolab/TOBIAS#219]
Dear all!
First of all I wanted to say that TOBIAS is great and easy-to-use tool!

I was wondering whether there is the possibility from either `PlotAggregate` or `PlotHeatmap` to obtain the scores for each position (not only the bed, but, for instance, the -60;+60bp range). Indeed `PlotAggregate` provides the scores, but they are already the average for all the regions.

Thank you in advance for your help!

**Comment by msbentsen** [comment]
Hi, 

Thank you for your interest in TOBIAS! Unfortunately we don't have a way to get the raw signal matrix within TOBIAS, but I can recommend you DeepTools computeMatrix instead (https://deeptools.readthedocs.io/en/develop/content/tools/computeMatrix.html).

If you use:
`computeMatrix reference-point -S <biwig file(s)> -R <bed file> -a 60 -b 60`
It should give you the values of the bigwigs within these regions.

Hope that helps you out!

**Comment by sebastian-gregoricchio** [comment]
Hi!
Thank you very much for your help!

Indeed, I already tried with it (and it works), but your tool was much faster in generating the plots (and therefore the matrix behind it I imagine) compared to deeptools. That's why I was wondering whether there was a way to get it from your tools in order to save some computation times.

Thank you anyway for you answer!
