### ISSUE TITLE
ATAC Correct not utlizing total memory

### ISSUE THREAD

**Issue by shankar2318** [loosolab/TOBIAS#225]
I am trying to run TOBIAS on my ATAC-Seq samples but it is taking way too long. So I checked the job stats and memory consumption.
`Maxvmem = 18.689G`
This is despite me providing TOBIAS with 150gb of memory
`qsub -l s_vmem=150G -l mem_req=150G -l d_rt=120:00:00 -l s_rt=120:00:00 -l medium tobias_3hr.sh`

Command used:
`singularity exec /usr/local/biotools/t/tobias\:0.13.3--py37h37892f8_0 TOBIAS ATACorrect --bam 3hr_merge.bam --genome dj_gen_mt.fa --peaks 3hr_peaks.narrowPeak --cores 1 --split 1 --outdir tobias_footprint/`

I have tried this with `split 1000` but it does it change the result. The memory consumption seems to be very low. I am trying to understand if I am doing something wrong? 

I have also tried allocating larger amount of memory but the `Maxvmem` usage does not change. For example, when I allocated 500gb memory
`Maxvmem = 25.586G`
I was able to complete this job however it took "14 hours 58 minutes".

This does not change for Scorebigwig and Binddetect either, the maxvmem usage is quite low.

Appreciate any help or guidance regarding this!

**Comment by msbentsen** [comment]
Hi @shankar2318 ,

The runtime of the tool is not necessarily limited by the memory. So even if you increase the memory to 500GB, the limiting factor is the computation itself. You can speed up the computation by increasing the `--cores` parameter to e.g. `--cores 8` in the run and this will also increase the memory consumption as individual threads are working in parallel. Hope that makes sense.

BR Mette

**Comment by shankar2318** [comment]
Thank you for the reply.

I apologize for not closing the thread, but I was able to solve it by increasing the core count.
