### ISSUE TITLE
'total_tfbs' column from BinDetect

### ISSUE THREAD

**Issue by Rajashree93** [loosolab/TOBIAS#226]
Could you please let me know where/how is the 'total_tfbs' column count derived from in the Bindetect results .xls files?

Secondly, could you also tell me how are the values in the '_change' column derived/calculated?

Thanks,
Rajashree

**Comment by msbentsen** [comment]
Hi Rajashee,

- `total_tfbs` refers to the total number of transcription factor binding sites in the input regions given to BINDetect. These correspond to the length of the individual `<TF>/beds/<TF>_all.bed`-files.
- The `_change` column is an effect-score between the raw differential footprint scores of the TF and the background sampled scores. Basically this shows whether there is an enrichment of TF-scores in condition 1 vs. 2 in comparison to background (similar to a log2fc) - there is a little bit more information to be found in the supplementary material of the TOBIAS paper here: https://www.nature.com/articles/s41467-020-18035-1#Sec22

You can also find information on the output formats on the wiki-page here: https://github.com/loosolab/TOBIAS/wiki/BINDetect
