### ISSUE TITLE
Correct matplotlib version for BINDetect?

### ISSUE THREAD

**Issue by beginnertobioinformatics** [loosolab/TOBIAS#227]
Hello, I am very new to using command-line tools, python, etc., so I apologize if this is a simplistic question.

I tried running BINDetect, but I get the following error: `AttributeError: 'Annotation' object has no property 'text_from_points'` 
I reran BINDetect with the test data, but I get the same error. I was wondering if there were specific versions of matplotlib and/or numpy that were necessary in order for BINDetect to work? I currently have matplotlib version 3.7.1 and numpy 1.25.0.

I ask about version compatibility specifically since I initially ran into errors when running PlotTracks, which were resolved once I edited the policy.xml file for Image-Magick-6 to allow for PDF to png conversion and downgraded PyPDF2 to version 2.12.1.

Any help is massively appreciated!

**Comment by msbentsen** [comment]
Hi @beginnertobioinformatics, did you figure this out? Otherwise there is an existing issue with a solution here: https://github.com/loosolab/TOBIAS/issues/221#issuecomment-1584191512

**Comment by beginnertobioinformatics** [comment]
Hello, yes, I found that same issue and tried downgrading adjustText, and it worked! Thank you!
