### ISSUE TITLE
Interpreting BINDetect _bound.bed files + Running CreateNetwork with JASPAR dimers

### ISSUE THREAD

**Issue by beginnertobioinformatics** [loosolab/TOBIAS#228]
Hello,

This is more of a conceptual clarification on BINDetect and the output "(condition)_bound.bed" files. I have two conditions (Control and Treatment) in my data and ran BINDetect to determine differential transcription factor binding between the two conditions. When looking at the treatment_bound.bed files, I was expecting that all of the peaks within which footprints were identified would be peaks that were called from either my Treatment sample data alone or were called for both my Control and Treatment samples. However, a fair amount of footprints in the treatment_bound.bed files seemed to fall within peaks that were only called for my Control sample. The opposite is also true for my control_bound.bed files-- a fair amount of the footprints there fall within peaks that were only called for my Treatment sample.

Is this normal? Or does this indicate that something is wrong with either my files/my analysis?

--
I also had a question regarding CreateNetwork. When I ran BINDetect, I used a file containing the JASPAR motifs identified for Mus Musculus as the --motifs input. As a result, some of the motifs are dimers (e.g. Fos::Jun) that don't map to a single Ensembl ID, which means that when running CreateNetwork, these dimers seem to be ignored. Is there any way that's typically recommended in order to bypass this issue?

Thank you so much for your insight! This pipeline has been so incredibly helpful and informative for me as a beginner to ATAC-seq!

**Comment by sufyazi** [comment]
Hello,

I am not Mette who is the dev of TOBIAS, but I can try pointing you to the right direction for your second question.

See [here](https://github.com/loosolab/TOBIAS/issues/201), a question I asked before. Basically, CreateNetwork does not currently handle these heterodimeric motifs.

**Comment by beginnertobioinformatics** [comment]
Thank you so much! I had thought this might have already been posted under "Issues," but missed that post when I was looking through. Thank you!

**Comment by msbentsen** [comment]
I would have answered exactly the same as @sufyazi, thank you! I will close this issue, but feel free to reopen in case it's not resolved.

**Comment by msbentsen** [comment]
> With regards to my first question about how footprints are being detected where peaks supposedly weren't called for said condition

Sorry, I missed the original question. Yes, it might happen that a peak is called for condition A but not for condition B, even though both are similar in signal - that depends on the peak-calling algorithm and how it chooses what is a peak or not. it might be a false negative. So since the input to TOBIAS is all peaks (merged from A and B), it can still happen that you find bound TFBS in condition B although the peak was not called. I would not worry too much about the origin of the peak and just refer to these as a "search field of open chromatin", which may or may not be open in that specific condition. Hope that makes sense.

**Comment by beginnertobioinformatics** [comment]
Thank you for the clarification!

**Comment by apal6** [comment]
Hi @msbentsen, I have a similar question,  I merged two samples (treatment and control bed files) that I want to compare and then ran the whole pipeline. I got the output but now i am trying hard to understand the output as both the conditions are showing similar output. Also, from the RNA-seq analysis I did, I found this TF to be enriched only in the treated group. But here, I am seeing the signal in the control sample too. Not sure what is happening?  Is there anything wrong with my analysis? 
Additionally, I also saw some TFs to be opposite (enriched in control) even after specifying the treated sample first in the --signals flag. here's the code:

`TOBIAS BINDetect --motifs /ATAC-seq/JASPAR2024_CORE_non-redundant_pfms_meme.txt \ --signals 2 treatment.bw control.bw \ --genome /genome/genome.fa \ --peaks merged_peaks.bed \ --outdir BinDetect_out`

Can you help?
Thank you!
