### ISSUE TITLE
Question about BinDetect log

### ISSUE THREAD

**Issue by amwa** [loosolab/TOBIAS#230]
Hi! While running BinDetect, I noticed that the following warning was given in the output log -- 
"[WARNING] Curve-fitting quantile normalization failed for 'cond_1'. Falling back to 'constant' normalization (factor = 1.03)." 
Could someone please explain what this means? What effect will the use of a different normalization method have on the output of BinDetect?
Thanks so much!

**Comment by msbentsen** [comment]
Hi @amwa ,

Thank you for your question! During the run, BINDetect will try to normalize all conditions to each other using quantile normalization. However, this normalization factor is different depending on the value, as higher footprint-scores tend to differ more between conditions. If you run BINDetect with the option `--debug`, you will get a file with some additional plots, for example:

<img src="https://github.com/loosolab/TOBIAS/assets/47495444/fffd3dae-8674-48a0-962e-e69a19fb4a02" width="300">   
 
and

<img src="https://github.com/loosolab/TOBIAS/assets/47495444/a42b6ff7-d6af-40f7-bd32-b5b90e6f9bdc" width="400">

Which shows the normalization factor needed for each condition, and can be used to debug potential issues. Maybe this will show why the algorithm was not able to fit the curve for the normalization?

But in conclusion, the BINDetect run should still show good results, but you might have some volcano-plots that are not well-balanced between condition A and B (e.g. all to one side etc.). So just keep that in mind when interpreting the results. Hope that helps 👍

**Comment by amwa** [comment]
Thank you for the explanation!

**Comment by msbentsen** [comment]
Hi @amwa ,

Just wanted to make you aware of an update to TOBIAS, which solves a bug with exactly this normalization step. I am not sure if this is exactly what happened here, but if you want, you might check the new version `tobias=0.16.0` to see if the error is gone and compare the results. The error was caused by an upgrade to the numpy package, but was now solved. 

BR Mette
