### ISSUE TITLE
Using Shifted .BED Files for ATACorrect?

### ISSUE THREAD

**Issue by ATACSeq-Qs** [loosolab/TOBIAS#232]
Hello,

Not an issue so much as a question--

I initially analyzed my ATAC-seq samples through the PEPATAC pipeline and am hoping to run TOBIAS now for downstream TF footprinting. As part of the PEPATAC workflow, peak calling is conducted on reads that have already had the +4/-5 positive and negative strand shifting, respectively, conducted on them. However, my .bam files have not been shifted. 

Can I still run TOBIAS ATACorrect with these my shifted .bed peaks file (or, is this in fact the norm-- are peaks files typically shifted anyway)? In case it is helpful, for the actual MACS2 peak calling, I have used the shift-extend method with the following parameters: "--shift -75 --extsize 150 --nomodel --call-summits --nolambda --keep-dup all -p 0.01."

Thank you so much in advance for your insight (and for creating such a well-documented, clear footprinting pipeline)!

**Comment by msbentsen** [comment]
Hi, thank you for the question and the nice words! Shifting the reads should have limited effect on the called peaks, especially since the read signal is extended to 150bp width during peak-calling and shifting is only +4/-5bp. So you are free to use peaks called on either shifted or unshifted .bam-files. 

The most important thing is to adjust `--read_shift` in `TOBIAS ATACorrect` if the reads are already shifted (default assumes they are not shifted).

**Comment by ATACSeq-Qs** [comment]
Thanks so much for the clarification!

**Comment by NathaneilKnight** [comment]
> Hi, thank you for the question and the nice words! Shifting the reads should have limited effect on the called peaks, especially since the read signal is extended to 150bp width during peak-calling and shifting is only +4/-5bp. So you are free to use peaks called on either shifted or unshifted .bam-files.
> 
> The most important thing is to adjust `--read_shift` in `TOBIAS ATACorrect` if the reads are already shifted (default assumes they are not shifted).

Hello,
I‘m wondering if other parameters, like bg_shift or k_flank, should be adjusted correspondingly when the input reads are already shifted. Only changing read_shift 4 -5 to 0 0 is OK?

**Comment by hschult** [comment]
You are correct. Adjusting `read_shift` is enough as `bg_shift` and `k_flank` are applied taking `read_shift` into account.
