### ISSUE TITLE
"change" field in bindetect_results

### ISSUE THREAD

**Issue by amwa** [loosolab/TOBIAS#233]
Hi, I might have missed this in the documentation somewhere, but what does the "cond1_cond2_change" field represent in the bindetect_results.txt table output by TOBIAS? Is this a subtraction of the mean score for condition 1 vs condition 2, a ratio, a log2 fold change, or something else?

**Comment by msbentsen** [comment]
Hi @amwa ,

You can find more information in the supplementary information of the TOBIAS paper, here: https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-020-18035-1/MediaObjects/41467_2020_18035_MOESM1_ESM.pdf

Basically the change score (differential binding score) is an effect size between the observed changes between condition1 and condition2 vs. the background changes:
![image](https://github.com/loosolab/TOBIAS/assets/47495444/707af59e-6c6b-4620-a97f-624d0004a8c9)
![image](https://github.com/loosolab/TOBIAS/assets/47495444/d792b292-c941-4954-88dc-7bc3a5a26596)

I hope that helps!
