### ISSUE TITLE
BINDetect .bed is not proper bed format

### ISSUE THREAD

**Issue by portbo** [loosolab/TOBIAS#236]
when running BINDetect I provide a bed file for --peaks and --peak_header. But even after formatting my bed file similar to  test_data/merged_peaks_annotated.bed I still get the error .bed is not proper bed format:

Can you kindly comment.

my bed file:
chr12 57751652 57752907 GCGR_E20.mRp.clN_peak_32546 150404 + exon exon
chr7 100585809 100586978 GCGR_E20.mRp.clN_peak_138165 87650 + promoter-TSS LRCH4
chr12 57771441 57773030 GCGR_E20.mRp.clN_peak_32550 84887 + promoter-TSS METTL1
chr7 75738704 75739896 GCGR_E20.mRp.clN_peak_136540 82924 + promoter-TSS CCL26
chr4 51842550 51843918 GCGR_E20.mRp.clN_peak_105972 79696 + promoter-TSS DCUN1D4
chr7 44082237 44083094 GCGR_E20.mRp.clN_peak_134728 77560 + promoter-TSS POLM
chr12 45989784 45991295 GCGR_E20.mRp.clN_peak_31529 74499 + promoter-TSS SCAF11
chr7 77798010 77799544 GCGR_E20.mRp.clN_peak_136771 73770 + promoter-TSS PHTF2
chr1 206202873 206203890 GCGR_E20.mRp.clN_peak_11879 73074 + promoter-TSS SRGAP2
chr7 25862155 25862877 GCGR_E20.mRp.clN_peak_133044 73021 + Intergenic

my header:
chrom chromstart chromend peak_id peak_score peak_strand gene_id gene_name

**Comment by msbentsen** [comment]
Hi @portbo ,

A few things you might check are:
- Are there "\t" (tab) between the columns in the file, or only spaces? .bed-files should be tab-separated
- Do all lines contain the same number of columns
- Are all positions proper .bed-coordinates, e.g. start is smaller than end coordinates

If you don't find the error, you are welcome to share parts of the file in raw format, then I will be happy to have a look.
