### ISSUE TITLE
About 0-based or 1-based?

### ISSUE THREAD

**Issue by tzhu-bio** [loosolab/TOBIAS#237]
Thanks for the TOBIAS, it was very helpful in my research. We know that the MACS2 output narrowpeak file starts with 0. 
I would like to ask if the footprint start coordinate is 0 or 1?

**Comment by msbentsen** [comment]
Hi @tzhu-bio ,

The TFBS files written by TOBIAS start with 0, but are start-exclusive and end-inclusive, meaning that the site:
`chr1  0  15` spans the bases 1-15 in the genome, and have a length of 15. Hope that helps.

**Comment by tzhu-bio** [comment]
Thanks a lot!
