### ISSUE TITLE
Issue with running TOBIAS BINDetect 

### ISSUE THREAD

**Issue by anu-bioinfo** [loosolab/TOBIAS#24]
Hello,

I am having issues running TOBIAS BINDetect. I get the following error -- 

Traceback (most recent call last):
  File "/mnt/NewHDD/anaconda3/bin/TOBIAS", line 8, in <module>
    sys.exit(main())
  File "/mnt/NewHDD/anaconda3/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/mnt/NewHDD/anaconda3/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 684, in run_bindetect
    fig = plot_bindetect(comparison_motifs, clustering, [cond1, cond2], args)
  File "/mnt/NewHDD/anaconda3/lib/python3.7/site-packages/tobias/tools/bindetect_functions.py", line 584, in plot_bindetect
    dendro_dat = dendrogram(cluster_obj.linkage_mat, labels=list(IDS), no_labels=True, orientation="right", ax=ax3, above_threshold_color="black", link_color_func=lambda k: cluster_obj.node_color[k])
  File "/mnt/NewHDD/anaconda3/lib/python3.7/site-packages/scipy/cluster/hierarchy.py", line 3278, in dendrogram
    raise ValueError("Dimensions of Z and labels must be consistent.")
ValueError: Dimensions of Z and labels must be consistent.

I am running the following command --

TOBIAS BINDetect --motifs MA0099.3.jaspar  --signals inhib_footprints.bw ctrl_footprints.bw --genome genome.fa --peaks peaks.bed  --outdir TOBIAS_BINDetect_output --cond_names Inhib Ctrl --motif-pvalue 0.05 --bound-pvalue 0.05 --cores 2

The bigwig files are obtained from 10x genomics scATAC-seq bam files, after running the two previous commands of the pipeline. Could you please hlep me out here ? 

Thanks in advance.

**Comment by anu-bioinfo** [comment]
Thanks for your response. So, I ran TOBIAS on the test data and could not reproduce the error. The following is the version number:
TOBIAS --version
0.11.6

Thanks

**Comment by msbentsen** [comment]
I can reproduce this for input `--motifs` files with only one motif. I will have a look at fixing this as soon as possible!

Until then, a quick fix for you would be to just add another motif to the `--motifs` file. This does not affect the results of the first motif, so you would still get the needed results for MA0099.3.jaspar. Sorry for the inconvenience!

**Comment by anu-bioinfo** [comment]
Thanks for your response. Yes, that was my initial guess. And then I reran TOBIAS BINDetect using all the motifs that I am interested in and it worked fine.

**Comment by msbentsen** [comment]
This was be fixed in TOBIAS 0.11.7 - closing, but please reopen in case of any issues.
