### ISSUE TITLE
ATACorrect error: Peak region was removed at it is either out of bounds or not in the chromosomes given in genome/bam

### ISSUE THREAD

**Issue by kkohl96** [loosolab/TOBIAS#240]
Hello,
I ran ATACorrect and got the following error for all the peaks in my bed file: "Peak region ('chr1', 911162, 911558, '', '.') was removed at it is either out of bounds or not in the chromosomes given in genome/bam".
Unfortunately, I couldn't figure out what the issue was since the peaks are also present in my bam file, I used the same genome (hg38) that was used for mapping and not only some, but all peaks gave the same error.
I would really appreciate your help if you ever experienced the same problem before or could think of a solution.
Thank you very much in advance!

**Comment by msbentsen** [comment]
Hi @kkohl96,

Yes, that indeed sounds a little strange - I didn't see that before. Is it possible for you to share the full log of the run with `--verbosity 4` as parameter? That might write out a little bit more information which is helpful to see what is going on here, thank you!

**Comment by kkohl96** [comment]
Hi @msbentsen,
I solved the problem already, I used chr in front of the chromosome numbers and that didn't work.
Thanks for offering your help!
Do you know how to delete this post?

**Comment by msbentsen** [comment]
Great, thank you for the update! No need to delete it, I will just close it so that other people can see it for reference :-)
