### ISSUE TITLE
module 'matplotlib.cbook' has no attribute 'mplDeprecation'   

### ISSUE THREAD

**Issue by liz-is** [loosolab/TOBIAS#244]
Hi,
I recently installed TOBIAS for a new project and had this issue:

```
$ TOBIAS --version                                        
Traceback (most recent call last):                                                                                 
  File "/home/egi12/.conda/envs/tobias/bin/TOBIAS", line 7, in <module>                                            
    from tobias.TOBIAS import main                                                                                 
  File "/home/egi12/.conda/envs/tobias/lib/python3.9/site-packages/tobias/TOBIAS.py", line 38, in <module>         
    warnings.filterwarnings("ignore", category=matplotlib.cbook.mplDeprecation)                                    
AttributeError: module 'matplotlib.cbook' has no attribute 'mplDeprecation'   
```

This is solved by downgrading to matplotlib 3.7.3 from 3.8.1, as was the case [here](https://stackoverflow.com/questions/77128061/ydata-profiling-profilereport-attributeerror-module-matplotlib-cbook-has-no).

**Comment by msbentsen** [comment]
Hi, thank you for this issue - please have a look at the closed issue here: https://github.com/loosolab/TOBIAS/issues/242#issuecomment-1792335548 

The error can be solved by downgrading matplotlib or by installing the beta version from the dev branch (until the new version is released).

**Comment by liz-is** [comment]
Whoops sorry, I forgot to check the closed issues first! I'll close this then as it's a duplicate. Good to know the next release has a fix already.
