### ISSUE TITLE
CreateNetwork issue:Subset 1269038 sites to 0 sites with a valid source id in the '--origin' table

### ISSUE THREAD

**Issue by kai333334** [loosolab/TOBIAS#251]
Hi,
  I'm trying to perfom the CreateNetwork, but it display the below words:
[WARNING] Subset 1269038 sites to 0 sites with a valid source id in the '--origin' table.
  Then I tried to find the issue, then I find that the bed files output by the BINDetect show the TFs with motif Serial number, like HOXB7_MA1501.2，but I saw it in the test data is only the TF names, so I guess it's the reason why I find 0 sites with matching target.

What should I do to remove the TFs serial number in bed files.

My English is poor, forgive me for my English writing mistakes.
Thank you very much.

**Comment by hschult** [comment]
Hi @kai333334,
thank you for using TOBIAS!

I think you are correct. By default, BINDetect will return `name_id` for the motifs. This does not match the `motif2gene_mapping.txt` of the test data, which only contains the motif name. Thankfully there is a parameter in BINDetect to change the output:
```
  --naming <string>          Naming convention for TF output files ('id', 'name',
                             'name_id', 'id_name') (default: 'name_id')

```
Could you please try to add `--naming name` to your BINDetect call and see if that fixes the issue?

Let me know if it worked.
Best wishes,
Hendrik

**Comment by kai333334** [comment]
Hi@hschult，
the parameter in BINDetect successfully changed the output.

I'm truly grateful for your help.
Best wishes,
KAI
