### ISSUE TITLE
BINDetect new adjustText error

### ISSUE THREAD

**Issue by NMaziak** [loosolab/TOBIAS#259]
Hello, 

I just wanted to post this as an extension to these issues: 
[(https://github.com/loosolab/TOBIAS/issues/182#issuecomment-1400273409)]
[(https://github.com/loosolab/TOBIAS/issues/221#issuecomment-1584191512)]

While running TOBIAS (v0.16.1) I got a different error stemming from the same culprit - adjustText: 

```
"/home/.conda/envs/atac/lib/python3.8/site-packages/matplotlib/artist.py", line 1197, in _update_props
    raise AttributeError(
AttributeError: FancyArrowPatch.set() got an unexpected keyword argument 'add_objects'
Traceback (most recent call last):
```

Downgrading it resolved it. I was wondering if this could be included in the [yaml](https://github.com/loosolab/TOBIAS/blob/main/tobias_env.yaml)?

Thanks again for creating and keeping up with such a nice tool! 

All the best, 
Noura Maziak

**Comment by mohobein** [comment]
Hello Noura,

thank you for your issue!
That is good to know, we will adjust the yaml to deal with this problem for the next release.

Best regards,
Moritz
