### ISSUE TITLE
Field names in bed output

### ISSUE THREAD

**Issue by elia427** [loosolab/TOBIAS#261]
Hi,

I have results from 10 conditions within a file - <outdir>/<TF>/beds/<TF>_all.bed. I understand that the last 20 columns represent scores for bound or unbound motifs, but I couldn't determine which column corresponds to each condition because the BED file lacks field names. Could you please assist?

Kind regards,
Elia

**Comment by mohobein** [comment]
Hey Elia,

thank you for your issue.
I am assuming you are talking about your `BINDetect` output. If you look one directory above the files you are talking about (the parent directory for each TF), you should find an `.xlsx` file. This file contains all columns from your file in question and some additional information. The columns are named here. If you are not depending on the .bed file format, your can read that file instead for the header. If you need to work with .bed files, the column order should be the same as in the excel file. You can check if that is really the case by comparing the values from both files.

I hope this answers your question. If you need additional help, feel free to ask!

Best regards,
Moritz

**Comment by elia427** [comment]
Hi Moritz,

Yes, that was exactly what I was looking for. Thank you for the help.

Kind regards,
Elia
