### ISSUE TITLE
bam and -peaks bed file in ATACorrect

### ISSUE THREAD

**Issue by 31474molly** [loosolab/TOBIAS#264]
Thank you for your great work!
I would like to ask if the genomic region of the bam file needs to be exactly the same as the range of peak.bed? my peak.bed is just a partial chromatin open region of the bam file.
Thank you so much,Sincerely

**Comment by mohobein** [comment]
Hey @31474molly,

thank you for using TOBIAS!

The peaks.bed file does not need to cover your entire input bam file. It is important that the bam file has sufficient read coverage in your peak regions for the analysis to work, but the peaks.bed file should pretty much always cover a subset of the genome only (as you said, just open chromatin regions, as they contain enough reads to provide a clear signal for the analysis).

I hope this answers your question!

Best regards,
Moritz

**Comment by 31474molly** [comment]
Thank you for your prompt reply!
Besides, I have five biological conditions. Is it recommended to merge the bam files of all biological duplicates for each biological condition and just run ATACorrect once for each biological condition?

Thanks in advance!
Best regards,
Molly

**Comment by mohobein** [comment]
Yes, your assumption is correct. TOBIAS does not deal with replicates and you should usually merge them per condition to have bam files with high read coverage.

Best regards,
Moritz
