### ISSUE TITLE
BINDetect warning and error

### ISSUE THREAD

**Issue by peryq** [loosolab/TOBIAS#266]
Thanks for providing this tool to the community.

I have encountered the following error "AttributeError: FancyArrowPatch.set() got an unexpected keyword argument 'add_objects'" using BINDetect (TOBIAS 0.16.1 BINDetect). Some warning messages include "has dtype incompatible with int64, please explicitly cast to a compatible dtype first. prob_df.loc[:, :] = vals / vals.sum(axis=1)[:, np.newaxis]" and "FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. "

There are some partial outputs from running BINDetect. Four files (bindetect_distances.txt, bindetect_figures.pdf (cant open),bindetect_results.txt, and bindetect_results.xlsx) plus the motif folders .

Please help with this!

Thanks!

**Comment by mohobein** [comment]
Hello @peryq,

thank you for using TOBIAS.

This looks like an error related to the `adjustText` package. Try downgrading it to `<0.8` and check if that allows BINDetect to run through without crashing. We have to update the environment yaml in the next release. 

If this does not solve your problem, we can investigate further.

Best regards,
Moritz

**Comment by peryq** [comment]
Hi @mohobein,

Thanks! After downgrading the adjustText, the BINDetect worked (mamba install  adjusttext==0.7.3.1).  

Some warning messages that don't affect the functionality include "tobias/lib/python3.10/site-packages/logomaker/src/matrix.py:270: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas" and "python3.10/site-packages/tobias/tools/bindetect.py:759: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`"

**Comment by StevenBai97** [comment]
> Hi @mohobein,
> 
> Thanks! After downgrading the adjustText, the BINDetect worked (mamba install adjusttext==0.7.3.1).
> 
> Some warning messages that don't affect the functionality include "tobias/lib/python3.10/site-packages/logomaker/src/matrix.py:270: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas" and "python3.10/site-packages/tobias/tools/bindetect.py:759: FutureWarning: Series.**getitem** treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`"

Hi,

I have also encountered the same warning messages like "/.conda/envs/tobias/lib/python3.12/site-packages/logomaker/src/matrix.py:270: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.2 0.5 0.3 0.2 0.6 0.7 0.6 0.2 0.4 0.6 0.4]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first. prob_df.loc[:, :] = vals / vals.sum(axis=1)[:, np.newaxis]".

Would they affect the results of the BINDetect?

Thanks in advance and all the best

**Comment by StevenBai97** [comment]
Hello @peryq @mohobein ,

I have also encountered the same warning messages like "/.conda/envs/tobias/lib/python3.12/site-packages/logomaker/src/matrix.py:270: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.2 0.5 0.3 0.2 0.6 0.7 0.6 0.2 0.4 0.6 0.4]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first. prob_df.loc[:, :] = vals / vals.sum(axis=1)[:, np.newaxis]".

Would they affect the results of the BINDetect?

Thanks in advance and all the best
