### ISSUE TITLE
Conda/Mamba bioconda installation fails

### ISSUE THREAD

**Issue by augeas** [loosolab/TOBIAS#274]
Installing via bioconda/mamba to ensure all dependencies are present:

```bash
git clone https://github.com/loosolab/TOBIAS.git
cd TOBIAS
mamba env create -f tobias_env.yaml
source activate TOBIAS_ENV
mamba install tobias -c bioconda
```
fails with the following error:

```
LibMambaUnsatisfiableError: Encountered problems while solving:
  - package tobias-0.15.1-py310hd6be1da_0 requires python >=3.10,<3.11.0a0, but none of the providers can be installed
```

However, trying to pin the Python version in `tobias_env.yaml` also fails, with errors regarding the `appdirs` package.

**Comment by hschult** [comment]
Hi @augeas,

unfortunately, I can not reproduce your error. However, from your error message, I gather that you are installing TOBIAS version 0.15.1. Our current version is 0.16.1. So please make sure that you are on the newest version.
If that doesn't fix the issue a workaround could be to install tobias using pip -> `pip install tobias`.

I hope I could help. Please let me know how it goes.
Hendrik

**Comment by augeas** [comment]
False alarm, though I *had* observed this locally and on our HPC cluster. `mamba clean -a -y` was enough to resolve this, but it's annoying that `mamba remove --name TOBIAS_ENV --all` wasn't enough...
`
