### ISSUE TITLE
Error at TOBIAS FormatMotifs step

### ISSUE THREAD

**Issue by Knetsy** [loosolab/TOBIAS#28]
Hi,

I am running the TOBIAS snakemake pipeline and I got an error at the TOBIAS FormatMotifs step. Looking at the [format_motifs.log](https://github.com/loosolab/TOBIAS/files/5193355/format_motifs.log) I am getting this error "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 11: invalid start byte". I have downloaded the TF motifs from JASPAR (JASPAR Core PFMs) containing individual PFMs and unzip them. This is the 
[snakemake.log](https://github.com/loosolab/TOBIAS/files/5193409/2020-09-09T090555.089221.snakemake.log) file and here is the [config file](https://github.com/loosolab/TOBIAS/files/5193456/Neur.D50.pos_vs_smNPCs.config.pdf) that I am using. If I look into the snakemake log file the argument `--format` is set to pfm and my PFMs are jaspar files (.jaspar). I try to set `FormatMotifs: "--format jaspar"` under the "Default module parameters" in the config file but it did not work.

Thanks!

Deborah

**Comment by Knetsy** [comment]
Hi,

I found my mistake. In the same folder where my PFMs are I still had the zip file from where they were coming frome.
Sorry for that!

Best,

Deborah

**Comment by msbentsen** [comment]
I'm glad you found the issue! The error is also not the best (it should probably say from which file the error occurs), so I will make some changes in a later version. Thanks for the report!
