### ISSUE TITLE
CreateNetwork empty output

### ISSUE THREAD

**Issue by asundaresan1** [loosolab/TOBIAS#282]
Hello,

I am working on non human data. I have created the motif2gene_mapping file from the GTF. 
I have edited the *bound.beds so that the gene name (column 4) matches the gene name (column 1) of the motif2gene_mapping file. Still the CreateNetwork outputs are empty.
Can you let me know if there should be any other changes to be made?
I am attaching the error log , motif2gene mapping file and one of the *bound.bed files.

[error.log](https://github.com/user-attachments/files/16355071/error.log)
[Rattus_Norvegicus_Ensembl_Rnor_6.0_r102_mapping.txt](https://github.com/user-attachments/files/16355076/Rattus_Norvegicus_Ensembl_Rnor_6.0_r102_mapping.txt)
[TGIF2_MA0797.1_TREAT1_bound.txt](https://github.com/user-attachments/files/16355078/TGIF2_MA0797.1_TREAT1_bound.txt)

**Comment by hschult** [comment]
Hi @asundaresan1,

in the `error.log` it tells that some of your ids don't exist in your mapping file aka origin table. The sites of not matching ids are then removed which in your case is all of them. I had a look at your mapping file and there is a whitespace after each motif name. I suspect tobias tries to match e.g. `Tgif2` to `Tgif2 ` which is not the same. So removing these trailing whitespaces should fix your problem.

Let me know if this solved it.

Kind regards,
Hendrik

**Comment by asundaresan1** [comment]
Hi Hendrik,

The whitespace was the issue. I am able to run CreateNetwork successfully.

Thanks
