### ISSUE TITLE
How to customize the colors of the profile plots of `TOBIAS PlotAggregate`?

### ISSUE THREAD

**Issue by danli349** [loosolab/TOBIAS#288]
Hello: 

The colors of the outputs of `TOBIAS PlotAggregate` are a blue-red gradient. How to change the color of each plot with a specific color?  

Thanks a lot

```{bash}
TOBIAS PlotAggregate --TFBS BINDetect_output/$1/beds/$1"_all.bed" \
--signals Tobias_out/Y_merged_corrected.bw \
Tobias_out/YA_merged_corrected.bw \
Tobias_out/YC_merged_corrected.bw \
Tobias_out/YAC_merged_corrected.bw \
Tobias_out/E_merged_corrected.bw \
Tobias_out/EA_merged_corrected.bw \
Tobias_out/EC_merged_corrected.bw \
Tobias_out/EAC_merged_corrected.bw \
--output footprint/$1"_footprint_comparison_all.pdf" \
--share_y both \
--plot_boundaries \
--signal-on-x
```
![image](https://github.com/user-attachments/assets/df391765-20db-47c1-809a-1f174a643c6e)

**Comment by hschult** [comment]
Hi @danli349,

unfortunately, this is not possible for `PlotAggregate`. However, it might be possible to edit the result pdf.

I hope that helps.

Best wishes,
Hendrik
