### ISSUE TITLE
Finding TF binding site and Motif in specific peaks

### ISSUE THREAD

**Issue by JestlinNg** [loosolab/TOBIAS#289]
Hi, 

I have specific peaks/region of interest across my samples where I want to find the TFs that is bounded to those region. I have the bed file of those regions obtained from the merged peaks file. Specifically, I have 2 peak regions. Would you suggest if the BINDetect function can be ran to detect the TFs that are bounded to these region? Or is running BINDetect manner would be too niche and not recommended? 

Thank you so much again.

**Comment by mohobein** [comment]
Hey @JestlinNg,

if I understand correctly, you are asking whether you can run BINDetect just with these 2 regions and nothing else in your input peak bed file, correct? I would advise against that, as the peaks are also used for normalization and having very few input peaks might skew this process as the regions might not accurately represent the technical differences between the samples. However, you can just use your BINDetect output with all peaks and then subset the TFBS to only show those within your peaks of interest. This can be done with `bedtools intersect` if you are interested in specific TFs. If you want to look at any TFBS in your regions of interest, it might be easier to use `TOBIAS SubMerge`, a new command line tool introduced in the newest version 0.17. It merges all TFBS across all TFs you want to include and returns only those in specified regions, If you want to do the same with bedtools, you'd have to create a file with all relevant TFBS yourself first, but that is also easily possible.

I hope this answers your question. If you have further need for help, let me know!

Best regards,
Moritz

**Comment by JestlinNg** [comment]
Dear Mortiz, thank you I understand. Thanks for the really useful tools btw!
