### ISSUE TITLE
No common contigs left to run ATACorrect on

### ISSUE THREAD

**Issue by arodel21** [loosolab/TOBIAS#291]
I am trying to run ATACorrect for a bulk scATAC-seq BAM file, but I get.

[ERROR]	No common contigs left to run ATACorrect on. Please check that '--bam' and '--fasta' are matching

The header of the BAM file is

@HD	SO:coordinate
@SQ	SN:1	LN:59578282
@SQ	SN:10	LN:45420867
@SQ	SN:11	LN:45484837
@SQ	SN:12	LN:49182954
@SQ	SN:13	LN:52186027
@SQ	SN:14	LN:52660232
@SQ	SN:15	LN:48040578
@SQ	SN:16	LN:55266484
@SQ	SN:17	LN:53461100
@SQ	SN:18	LN:51023478
@SQ	SN:19	LN:48449771
@SQ	SN:2	LN:59640629
@SQ	SN:20	LN:55201332
@SQ	SN:21	LN:45934066
@SQ	SN:22	LN:39133080
@SQ	SN:23	LN:46223584
@SQ	SN:24	LN:42172926
@SQ	SN:25	LN:37502051
@SQ	SN:3	LN:62628489
@SQ	SN:4	LN:78093715
@SQ	SN:5	LN:72500376
@SQ	SN:6	LN:60270059
@SQ	SN:7	LN:74282399
@SQ	SN:8	LN:54304671
@SQ	SN:9	LN:56459846
@SQ	SN:MT	LN:16596

While the genome has chromosomes 1,2,3,4,5,..,MT, without the prefix "chr".

I don't really see why it fails.
I would very much appreciate your help.

**Comment by mohobein** [comment]
Hello @arodel21,

from the example you provided, I suspect the issues might be related to the way the chromosomes are ordered. The chromosomes in your bam file are sorted alphabetically (i.e. as if the numbers were string -> 1, 12, 2, ...)  while the chromosomes in your genome file are sorted numerically (i.e. 1, 2, ..., 12).

Could you try to sort them both properly in the same order and run the command again? If the error persists, we can investigate further.

Kind regards,
Moritz

**Comment by arodel21** [comment]
Thank you @mohobein! You are absolutly right! I didn't sort it, but just changed the genome reference file and it worked haha
