### ISSUE TITLE
Including more normalisation methods for the reads

### ISSUE THREAD

**Issue by arodel21** [loosolab/TOBIAS#292]
Hello!

Thank you so much for your amazing work!

I just wanted to know if it is possible to add more normalization methods, such as TPM, to the read counts before outputting the bigwig file. Or are there any plans of including more methods soon?

Thanks in advance!

**Comment by hschult** [comment]
Hi @arodel21,

unfortunately, we are not planning on adding any more normalization methods. The method you mentioned (TPM) is an RNA-based normalization that corrects for gene length so it would need some adjustments before it can be used on ATAC data.
However, there is still a way for you to apply a normalization method of your choice to the ATACorrect output. As mentioned [here](https://github.com/loosolab/TOBIAS/issues/54) you can use `--norm-of` to disable the integrated normalization. ATACorrect will then output bigwigs containing the "raw" counts, which you can normalize using a different method. Afterwards, you can proceed with the TOBIAS analysis.

I hope that helps,
Hendrik

**Comment by arodel21** [comment]
Thank you @hschult! I will do that.
Best wishes.
