### ISSUE TITLE
BINDetect fails to read motif scanning .tmp file

### ISSUE THREAD

**Issue by msbentsen** [loosolab/TOBIAS#31]
Here's the full log (err and out)

TOBIAS cannot find a tmp file. It's not a write permission nor a storage quota issue.

Perhaps I should have created a different issue, but since this open was open and with the same error message, I kind of hijacked it. Please tell me if I have to open a new issue or not.

[grichard.1522399.out.txt](https://github.com/loosolab/TOBIAS/files/5268268/grichard.1522399.out.txt)
[grichard.1522399.err.txt](https://github.com/loosolab/TOBIAS/files/5268269/grichard.1522399.err.txt)

_Originally posted by @gtrichard in https://github.com/loosolab/TOBIAS/issues/30#issuecomment-697352670_

**Comment by msbentsen** [comment]
Hi, would it be possible for you to run the call with "--verbosity 4"? E.g. ` TOBIAS BINDetect --signals ../../Denis/FAIRE-seq/BWs.mean/T0_FAIRE_l2r.mean.bw ../../Denis/FAIRE-seq/BWs.mean/T1A_FAIRE_l2r.mean.bw ../../Denis/FAIRE-seq/BWs.mean/T2A_FAIRE_l2r.mean.bw ../../Denis/FAIRE-seq/BWs.mean/T3A_FAIRE_l2r.mean.bw ../../Denis/FAIRE-seq/BWs.mean/T1K_FAIRE_l2r.mean.bw ../../Denis/FAIRE-seq/BWs.mean/T2K_FAIRE_l2r.mean.bw ../../Denis/FAIRE-seq/BWs.mean/T3K_FAIRE_l2r.mean.bw --peaks peaks_197k.bed --motifs conserved_Dmel_TF_in_Apisum.meme --genome ../../../Apisum/assembly2_accnum_noempty.fasta --outdir TOBIAS --verbosity 4` in your working directory? This will print more debugging messages to the stdout log.

I am not exactly sure what is going on, but the increased logging might help to uncover it :-)

**Comment by gtrichard** [comment]
Hi @msbentsen , thanks for openning a new issue. Here's the outcome with `--verbosity 4` added.

[grichard.1525398.out.txt](https://github.com/loosolab/TOBIAS/files/5310600/grichard.1525398.out.txt)
[grichard.1525398.err.txt](https://github.com/loosolab/TOBIAS/files/5310601/grichard.1525398.err.txt)

**Comment by msbentsen** [comment]
Hi @gtrichard, thank you for the logfiles - they were very helpful!

The issue arises because you have duplicate motif names in `--motifs` (e.g. for AbdA_Cell_FBgn0000014). Therefore, the temporary file for the first occurrence has already been removed once the second (the duplicate) one should be processed. I apologize for the inconvenience - this should definitely be handled better within TOBIAS, so I will be releasing a fix as soon as possible.

In the meantime, you can solve this by adding `_1`, `_2` or similar to the motif IDs, as is also done for some of the motifs already.

**Comment by gtrichard** [comment]
Thanks! I'll try this and let you know if it fixes the issue.

**Comment by msbentsen** [comment]
This was solved in `TOBIAS 0.12.2`. Let me know if you encounter any other issues!
