### ISSUE TITLE
The defalut threshold in differential plots

### ISSUE THREAD

**Issue by shangguandong1996** [loosolab/TOBIAS#35]
Hi, Dear developer 
I have got a volcano plot, but I am not sure what the threshold between the NS and significant. Is it -log10(p-value) > 75 and abs(binding score) > 0.1 ?

![图片](https://user-images.githubusercontent.com/22555126/96214079-2c2f7a80-0fad-11eb-955e-48ec6ff69c4d.png)

Best wishes
Guandong Shang

**Comment by msbentsen** [comment]
Hi Guandong,

The highlighted points are always set to be any TF below/above the 5th and 95th percentile of the differential binding scores or above 95th percentile of the -log10(p-value). Therefore, the threshold might differ per dataset, but will always show the most enriched TFs in either direction.

Best regards,
Mette

**Comment by shangguandong1996** [comment]
Get it :) 
And I have another question.Is the Solid circle means the most enriched TFs ( below/above the 5th and 95th) ?
![图片](https://user-images.githubusercontent.com/22555126/96232501-94d92000-0fca-11eb-86e4-a11bb9cfd13c.png)

**Comment by msbentsen** [comment]
Yes exactly - the solid circles represent TFs enriched in top plot (the ones also shown with labels).

**Comment by shangguandong1996** [comment]
Thanks ：）
