### ISSUE TITLE
Docker image...

### ISSUE THREAD

**Issue by Rosmaninho** [loosolab/TOBIAS#40]
Hello! I was interested in knowing if you plan releasing a Docker image?

**Comment by jenzopr** [comment]
Hi! Since TOBIAS is included in the bioconda channel for the conda package manager, there is also a corresponding biocontainer available: https://biocontainers.pro/#/tools/tobias 

I just noticed that it does not come with the latest version. Let me check if I can trigger an update at biocontainers..

**Comment by Rosmaninho** [comment]
Thank you so much for replying!!! You can´t imagine how much this is a life saver.
I will provide feedback as soon as possible. Tell me if it's updated so that I can pull the correct image.

**Comment by Rosmaninho** [comment]
With shifterimg -v  pull quay.io/biocontainers/tobias:0.11.3--py36h785e9b2_0 it fails to pull the image.

**Comment by Rosmaninho** [comment]
Never mind. It was an issue in my institution cluster setup. It does not accept images from sources other than Docker so we had to rebuild your image in Dockerhub to pull it.

**Comment by jenzopr** [comment]
Images of all previous versions are located here: https://quay.io/repository/biocontainers/tobias?tab=tags and can be pulled with Docker..

**Comment by Rosmaninho** [comment]
Weird, when I check on https://biocontainers.pro/#/tools/tobias it doesn't show the latest ones...

**Comment by jenzopr** [comment]
Yes, thats true. It seems that biocontainers is only a secondary source, where containers are stored. The primary is quay.io, so its most reliable to look there for the latest versions :-)
