### ISSUE TITLE
Running BINDetect with bed with 6 columns

### ISSUE THREAD

**Issue by Rosmaninho** [loosolab/TOBIAS#46]
I am trying to run BINDetect with a bed with columns with ENSEMBL Gene ID and Gene symbol, besides the usual genomic coordinates columns and the Peak_ID coordinates.
However, I always get this error and the run does not complete:

2020-11-27 16:55:33 (95469) [INFO]	Processing scanned TFBS individually
2020-11-27 16:55:33 (95469) [INFO]	Progress 0%
2020-11-27 16:55:33 (95469) [INFO]	Progress 16.31%
2020-11-27 16:55:33 (95469) [INFO]	Progress 40.77%
2020-11-27 16:55:33 (95469) [INFO]	Progress 68.67%
2020-11-27 16:55:33 (95469) [INFO]	Progress 69.1%
2020-11-27 16:55:33 (95469) [INFO]	Progress 93.13%
2020-11-27 16:55:33 (95469) [INFO]	Progress 98.71%
2020-11-27 16:55:34 (95469) [INFO]	Progress 100.0%
2020-11-27 16:55:34 (95469) [INFO]	Progress done!
2020-11-27 16:55:34 (95687) [ERROR]	Multiprocessing logger lost connection to queue - probably due to an error raised from a child process.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/tobias/tools/bindetect_functions.py", line 402, in process_tfbs
    line[condition + "_score"] = float(line[condition + "_score"])
KeyError: 'cell2_score'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.12.6', 'console_scripts', 'TOBIAS')())
  File "/usr/local/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/usr/local/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 605, in run_bindetect
    results = [task.get() for task in task_list]
  File "/usr/local/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 605, in <listcomp>
    results = [task.get() for task in task_list]
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
KeyError: 'cell2_score'
srun: error: compute-2: task 0: Exited with exit code 1
srun: Terminating job step 1297082.0

A file with the exact same coordinates but with only 4 columns completes the run. The test bed merged_peaks_annotated.bed completes the run. I'm at a loss to what I am doing wrong.

**Comment by Rosmaninho** [comment]
My purpose is to then take the output to CreateNetworks. Yesterday I tried to run CreateNetwork but since I didn't have gene_id nor identifier in the .bed file I think that the tool wasn't working.

**Comment by msbentsen** [comment]
Can you give me a little bit more information on what your input `--peaks` .bed-file looks like? Maybe post an example? 

And just to be clear: you are saying that with the exact same coordinates (only 4 columns) the run completes. Using the test-data, which contains 8 columns, it also completes. But with 6 columns, it creates the above KeyError. It seems a bit strange to me, but I am sure that we can figure it out!

**Comment by Rosmaninho** [comment]
Hey, I got back to this since I want to run Bindetect with different bound-pvalue. 
Here's an example of the bed file that I am using:

chr4	121165451	121165543	Peak_123568	ENSG00000050730	TNIP3
chr19	4153305	4153772	Peak_71228	ENSG00000060566	CREB3L3
chr3	8501452	8501954	Peak_101250	ENSG00000071282	LMCD1
chr3	48661456	48662078	Peak_103336	ENSG00000008300	CELSR3
chr3	48655676	48656778	Peak_103335	ENSG00000008300	CELSR3
chr19	44748959	44749092	Peak_73446	ENSG00000069399	BCL3
chr10	3782330	3783107	Peak_14978	ENSG00000067082	KLF6
chr10	3783259	3783468	Peak_14979	ENSG00000067082	KLF6
chr7	97877639	97877899	Peak_159865	ENSG00000070669	ASNS
chr17	47733018	47733556	Peak_63798	ENSG00000073861	TBX21
chr17	47720955	47721713	Peak_63797	ENSG00000073861	TBX21
chr6	46085765	46086347	Peak_142924	ENSG00000112782	CLIC5
chr7	107879321	107879792	Peak_160603	ENSG00000091140	DLD
chr7	107874605	107874888	Peak_160602	ENSG00000091140	DLD
chr7	107856967	107857424	Peak_160601	ENSG00000091140	DLD
chr19	3484998	3485348	Peak_71165	ENSG00000095932	SMIM24
chr22	30267012	30267483	Peak_99488	ENSG00000099985	OSM
chr22	37148440	37148690	Peak_99754	ENSG00000100385	IL2RB

I provide the following headers.txt

peak_chr	peak_start	peak_end	peak_ID gene_id gene_name

**Comment by Rosmaninho** [comment]
It's just that I want to use CreateNetworks, so I am providing Ensembl_IDs and Gene_Symbol columns. It facilitates a LOT my work downstream. I really don't know why it isn't working. :(

**Comment by Rosmaninho** [comment]
2020-12-11 09:39:58 (163947) [INFO]	Progress done!
2020-12-11 09:39:58 (164164) [ERROR]	Multiprocessing logger lost connection to queue - probably due to an error raised from a child process.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/site-packages/tobias/tools/bindetect_functions.py", line 402, in process_tfbs
    line[condition + "_score"] = float(line[condition + "_score"])
KeyError: 'Tconv_score'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/TOBIAS", line 33, in <module>
    sys.exit(load_entry_point('tobias==0.12.6', 'console_scripts', 'TOBIAS')())
  File "/usr/local/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 605, in run_bindetect
    results = [task.get() for task in task_list]
  File "/usr/local/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 605, in <listcomp>
    results = [task.get() for task in task_list]
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
KeyError: 'Tconv_score'
srun: error: compute-2: task 0: Exited with exit code 1
srun: Terminating job step 1311177.0

**Comment by Rosmaninho** [comment]
I managed to run it but I had to add two columns to the bed file to the following format:

chr4 121165451 121165543 TNIP3 . . ENSG00000050730 Peak_123568 
chr19 4153305 4153772 CREB3L3 . . ENSG00000060566 Peak_71228

This information should be available in the wiki. It's not clear that the bed file needs to have specific formats.

**Comment by msbentsen** [comment]
I am happy that you got it running, but also confused as to how that was the solution. I have set up a test case using the test_data (downloaded as covered in the wiki [here](https://github.com/loosolab/TOBIAS/wiki/test-data)).
 
Running the following commands, we can setup files with the same format as yours above (which you say fail):
```
$ cut -f 1,2,3,4,7,8 test_data/merged_peaks_annotated.bed > 6_column.bed 
$ cut -f 1,2,3,4,7,8 test_data/merged_peaks_annotated_header.txt > 6_column_header.txt
$ head 6_column.bed
chr4    74462   74662   Tcell   ENSG00000272602 ZNF595
chr4    124230  125676  Bcell,Tcell     ENSG00000250312 ZNF718
chr4    225107  225307  Tcell   NA      NA
chr4    242142  242604  Bcell,Tcell     NA      NA
chr4    284925  285125  Tcell   ENSG00000186777 ZNF732
chr4    306602  306957  Bcell   ENSG00000186777 ZNF732
chr4    329882  330359  Bcell,Tcell     ENSG00000131127 ZNF141
chr4    337178  338331  Bcell,Tcell     ENSG00000131127 ZNF141
chr4    418489  418689  Tcell   ENSG00000182903 ZNF721
chr4    424541  424741  Tcell   ENSG00000182903 ZNF721
$ cat 6_column_header.txt
peak_chr        peak_start      peak_end        peak_id gene_id gene_name
```

Using `version 0.12.6`, this test case runs without errors on these files:
```
$ TOBIAS BINDetect --motifs test_data/motifs.jaspar --signals test_data/Bcell_footprints.bw test_data/Tcell_footprints.bw --genome test_data/genome.fa.gz --peaks 6_column.bed --peak_header 6_column_header.txt --outdir test_output --cores 8
```

It does not seem that the .bed-format is the issue, so I don't believe that I _should_ update anything in the wiki. If anything should end up being wrong, I would prefer to be asked nicely to make any changes :-)

Best regards,
Mette

**Comment by Rosmaninho** [comment]
I wasn't trying to be snarky nor anything. I'm sorry if that's how it conveyed to you.
I am really puzzled by this issue. Maybe I can send you the .bed file that I used. I think the issue was the 4th column in my bed file with the Peak_IDs.
Something about the Peak_xxxx might've interfered? When I changed the order of the columns and moved that column, then it worked. I didn't try that on a 6 column file since I got it running, but I can try it again.

I do love Tobias, and I commend you for it. It was a life-saver to me. You can't imagine how much time you've saved me. :)
I would donate you for a beer (in the good open-source spirit) if you had a Patreon account or something. xD

**Comment by msbentsen** [comment]
Thank you, no worries :-) We don't have a Patreon for beer though, haha, but I will take the complement as payment! 

And yes, you are welcome to send me the .bed-file - either here if you are okay to share or to mette.bentsen@mpi-bn.mpg.de. I can't imagine that it is something about the Peak name, but maybe there is something else about the format. I will have a look.
