### ISSUE TITLE
BINDetect running with 2 bed file

### ISSUE THREAD

**Issue by Arda19corum** [loosolab/TOBIAS#51]
İ am comparing atac seq datas of 2 conditions.(Lets say A and B)

Do I need to merge 2 different bed files for --peaks input? Should I use A.bed and B.bed separetely in BINDetect or combine the 2 bed files of condition A and B with bedtools merge and use it like that?

What is the merged_peaks.bed exactly?

**Comment by msbentsen** [comment]
Yes, the `--peaks` input should be A.bed + B.bed (e.g. using bedtools merge as you mention), if the input bigwig files are "A.bw" and "B.bw". From the test data, merged_peaks.bed were created exactly like this, by merging the peaks of Bcell and Tcell condition peaks (source of data [here](https://github.com/loosolab/TOBIAS/wiki/test-data)).

As explained in the [wiki](https://github.com/loosolab/TOBIAS/wiki/BINDetect), the only thing to be aware of is that the footprints (the input signals) should be calculated for the same peaks e.g. that the --peaks input for `ATACorrect` and `ScoreBigwig` is the same as for `BINDetect.` That way, you are certain that scores are available for comparison.

Best Mette
