### ISSUE TITLE
BINDetect significance cut-offs for differential binding

### ISSUE THREAD

**Issue by vkartha** [loosolab/TOBIAS#58]
Hi,
   Thank you for making a very useful and intuitive package! I was curious, from the BINDetect output, and with the new html reports, the scatter (volcano) plots show TFs grouped as significant and non-significant differential TF motifs given the data. I'm aware that the pvalue is based on the statistical test against a background model, but what cut-off is used here (on both axes) to call something as significant in either direction?
   
   Thank you again in advance!

**Comment by msbentsen** [comment]
Hi @vkartha,

The threshold is set at the TFs with -log10(p-value) above the 95% quantile and/or differential binding scores smaller/larger than the 5% and 95% quantiles (top 5% in each direction). The threshold for significant factors can therefore change with each run depending on the data, so the label "significant" is maybe a bit misleading here - it is rather a set of "highlighted factors". 

Hope this answers your question!

**Comment by vkartha** [comment]
Thanks, very helpful!

**Comment by Rosmaninho** [comment]
So, I wanted to make an Enhanced volcano of my results instead of using the volcano output from Tobias. Do you have any feedback on how to define cut-offs?
Thank you in advance.
