### ISSUE TITLE
BindDetect - p-value of condition1_condition2_log2fc per footprint

### ISSUE THREAD

**Issue by Rosmaninho** [loosolab/TOBIAS#60]
Hello,

The output of BindDetect produces an overview.txt file for each PWM provided. This overview.txt has several columns, with the last column being the condition1_condition2_log2fc.
I would like to know if there's a p-value for each of the footprints produced? 
There's a log2fc for all the footprints of a certain PWM. What about for each of the footprints of a PWM?

**Comment by msbentsen** [comment]
Hi,
No, unfortunately there is no p-value for the individual sites, as that would require multiple values per site (or another type of estimation of variability, which is not in BINDetect as it is now). Instead, every site has a log2FC which can be used to sort and make selections like "The top 500 changed sites".

Best Mette
