### ISSUE TITLE
Broad settings MACS2

### ISSUE THREAD

**Issue by WardDeb** [loosolab/TOBIAS#61]
Hi,

Thanks for the software, I find it intuitive to use and it's very well documented.
While reading the paper as well as the wiki page, I noticed that for peak calling you use MACS2 in the broad setting. I cannot really speak out of experience, but from literature it seems most people tend to use the standard setting (e.g. narrowpeaks) for ATAC seq data. Is there a specific reason why the broad setting would be preferred with regards to downstream analysis using the TOBIAS framework ?

Kind regards,

Ward

**Comment by msbentsen** [comment]
Hi Ward,

From reading the MACS2 documentation, I found that the --broad setting is supposed to allow merging of nearby peaks over a certain threshold, so I have it on to allow for multiple minor peaks (let's say in a promoter) is merged to a larger region. So this flag should cover the scenario where the chromatin is in more of an "open" configuration, and not necessarily containing well-defined peaks. But to be honest, I have not made any extensive testing of this, so there is no deeper meaning behind it. I think the narrowpeaks are going to work just as well with TOBIAS!

Best Mette

**Comment by WardDeb** [comment]
Hi Mette,

Great, thanks for the information.

Kind regards,

Ward
