### ISSUE TITLE
Preprocessing of Data: MACS2 output

### ISSUE THREAD

**Issue by Hypercruse** [loosolab/TOBIAS#63]
We are a group of students studying at the Technical University of Munich, and we are trying to recreate some of your work using TOBIAS as a student project for a module we are currently taking.

First of all, thanks for that great documentation, it's really helping us quite a lot! 

We have 2 questions regarding peak calling using MACS2 and we hope you could maybe assist us:

1) MACS2 with the parameters stated in your documentation produces 3 output files, a .xls-file, a .broadPeak-file and a .gappedPeak-file. Which one of those do you use for further processing (e.g. for the merged_peaks.bed file used in ATACorrect. example for the merged_peaks.bed is in the test_data provided by your documentation) 

2) Which tool did you use to combine the bed files obtained by MACS2 for different conditions to create merged_peaks.bed

We hope this is the right place to ask you, sorry for bothering you if it's not! 
Thanks in advance

**Comment by jenzopr** [comment]
Wow, thats great! Thanks for reaching out. Out of curiosity: May I ask which practical / lecture you're attending? Who is the lecturer? Is it a bachelor or masters course? We're currently running a practical at another university as well and your experience and insights along the way will help to further improve TOBIAS and its tutorials. 

Regarding your questions, I'm sure @msbentsen will answer to your full satisfaction :-)

**Comment by Hypercruse** [comment]
Thanks for the quick reply! :)

We are currently in our 5. Semester of the bachelor's degree. It's a degree shared by the TUM and the LMU (the two largest universities of Munich). The practical is led by  [Prof. Dr. Ralf Zimmer](https://www.bio.ifi.lmu.de/mitarbeiter/ralf-zimmer/) and called "Genomorientiertes Bioinformatisches Praktikum" which roughly translates to genome-oriented bioinformatics practical. 

Part of this module is (for our team) to comprehend & recreate the findings of TOBIAS, and maybe (if we are able to implement it correctly of course :) ) add some extensions to it. Our first step right now is to use the fastq-files your documentation provides, run the different tools you used (like star, adaptcut, macs2, ...) and hopefully be able to get some comparable results. Afterwards, we are planning to use some of the ATAC-Seq the lecture provides and analyze it with TOBIAS. If the results are promising, we plan to work on some downstream extensions

We would be more than happy to share our experiences and insights about recreating your work!

**Comment by msbentsen** [comment]
That sounds like a very cool project! First, for your two original questions:

1. We use the .broadPeak files, as these represent the full peaks. It might be helpful for you to have a look at the snakemake pipeline for TOBIAS [here](https://github.molgen.mpg.de/loosolab/TOBIAS_snakemake). Snakemake is a workflow language for stringing together tools to a pipeline, and this pipeline starts with the .bam-files and does merging, peak calling and run the TOBIAS tools automatically. It is sometimes a bit hard to see within the code, but [here ](https://github.molgen.mpg.de/loosolab/TOBIAS_snakemake/blob/0e2cf3ef30be7f724015b898281b9a6a297903ed/snakefiles/preprocessing.snake#L103-L122) it is shown how the .broadPeak are used.

2. For merging the peaks, we use `bedtools merge` (link to the snakemake code [here](https://github.molgen.mpg.de/loosolab/TOBIAS_snakemake/blob/0e2cf3ef30be7f724015b898281b9a6a297903ed/snakefiles/preprocessing.snake#L128-L145) as well). Most importantly, bedtools merge only works on sorted files, so we do `cat <.bed-files> | sort -k1,1 -k2,2n |  bedtools merge` to enable that. We also remove the chipseq-blacklisted regions from this file using `bedtools subtract`.

I hope this helps you, and you are also more than welcome to contact us further here or via mail (should be in the README) :-)
