### ISSUE TITLE
Support for PWM files?

### ISSUE THREAD

**Issue by JKoester-1** [loosolab/TOBIAS#70]
Dear msbentsen,

Thank you for the development of this great tool and being so active in maintaining and improving it. I was wondering if it would be possible to use PWM files from:  http://humantfs.ccbr.utoronto.ca/ ?

Best,
Janis

**Comment by msbentsen** [comment]
Hi Janis,

Not directly, as TOBIAS only supports JASPAR/MEME-style motifs. But luckily, the format is pretty easy to convert to meme format! I downloaded the individual motif PWMs as given on [http://humantfs.ccbr.utoronto.ca/download.php](http://humantfs.ccbr.utoronto.ca/download.php), and created a file [here](https://gist.github.com/msbentsen/cff318af7965b9fcd61d8623635d8e2a) with the converted motifs in .meme format (and the source code snippet [here](https://gist.github.com/msbentsen/216b1d6918c48668622e0e0c0ff6ad77)). Please adjust the motifs/code to your liking.

I would not recommend running TOBIAS on all 5000+ motifs, so you can probably adjust the input list or make other filters to fit your application. Let me know of any issues, thanks!

**Comment by JKoester-1** [comment]
That's great! Thank you!
