### ISSUE TITLE
apply TOBIAS to Cynase-seq data

### ISSUE THREAD

**Issue by yushengak47** [loosolab/TOBIAS#73]
Hi,

Thank you for developing this amazing tool. I just want to known is it possible to apply TOBIAS to Cynase-seq data.

I expect that footprinting using ATAC-seq and DNase/Cynase-seq data are generally similar, except that the enzymes introduce different cleavage bias and should be specifically corrected. I wonder running ATACorrect with setting --read-shift 0 0 followed by other TOBIAS steps will generate reasonable Cynase footprint?

YU Sheng

**Comment by msbentsen** [comment]
Hi YU Sheng,

I am not familiar with Cyanase-seq data, or the technical background of the assay, so I am not sure if it will create a footprint - but theoretically, with `--read-shift 0 0 `it should be possible to correct the data. 

This paper for another bias-correction method shows a figure correcting Cyanase bias to show a footprint: https://academic.oup.com/nar/article/46/2/e9/4602870, but as said, I didn't try it with TOBIAS yet. But I would be very interested in your experience if you try it out!

Best Mette

**Comment by yushengak47** [comment]
Hi Mette,

Thanks for your quick reply. I will give it a try. I also have a high quality ChIP-seq data set, it might be helpful for evaluating the result. I'll get back to you later.


Best,

YU Sheng
