### ISSUE TITLE
bindetect results 

### ISSUE THREAD

**Issue by jmzvillarreal** [loosolab/TOBIAS#79]
Hi,
I have a few questions on some of the features found in bindetect results excel sheet and the figures ... 
In the dendrogram what is the threshold used to mark a TF as solid colored circle or not ?  
In the excel there is a sheet for individual TFs and another for TF clusters ... How are these clusters defined exactly ? They correspond to the colored  ones found in the dendrogram ?
Thanks very much in advance.
Jaime.

**Comment by msbentsen** [comment]
Hi Jaime,

The threshold is set dynamically for each run as:
> The threshold is set at the TFs with -log10(p-value) above the 95% quantile and/or differential binding scores smaller/larger than the 5% and 95% quantiles (top 5% in each direction). The threshold for significant factors can therefore change with each run depending on the data, so the label "significant" is maybe a bit misleading here - it is rather a set of "highlighted factors".

(from https://github.com/loosolab/TOBIAS/issues/58#issuecomment-776097421)

For the clusters, yes exactly - the clusters represent TF groups with similar motifs (=overlapping binding sites), as is seen in the dendrogram. All values are given as the mean of values of the included motifs. Under the "Individual motifs"-sheet, the column "cluster" tells you exactly which TFs are included in each cluster. Hope this answered your question!

Best Mette

**Comment by jmzvillarreal** [comment]
Thanks !! It did !
Best,
Jaime.
