### ISSUE TITLE
Input files for BINDetect

### ISSUE THREAD

**Issue by msbentsen** [loosolab/TOBIAS#8]
Hi Mette,
I am using the function of Bindetect. Where can I get my motif file? and also what is the bed file that containg all the peaks? how can I get? I am sorry. I am quit new to coding.

Best wishes
Xiaohan

_Originally posted by @xiaohanhe2020 in https://github.com/loosolab/TOBIAS/issues/6#issuecomment-601449811_

**Comment by msbentsen** [comment]
Hi @xiaohanhe2020,

I just created a new issue to keep the questions separate. To answer your question:
- The motif file is a file containing any TF motifs in common formats (jaspar/pfm/meme). You can download this file from public databases such as JASPAR ([link to download](http://jaspar.genereg.net/downloads/)).

- The peaks file is a .bed-file of ATAC-seq peaks. You can use a peak-caller such as MACS2 to get these per sample/condition. The important thing is that the peaks cover all conditions you want to compare. So if you did peak-calling separately per sample/condition, you can use `bedtools merge` to merge the different peak sets.

Hope these answers help you out!

**Comment by xiaohanhe2020** [comment]
Thank you very much for your reply Mette,
It is very helpfu. May I ask you another question? How can you get the annotated peaks.bed file?

Best wishes
Xiaohan

**Comment by xiaohanhe2020** [comment]
Hi Mette.
Can I use homer instead of UROPA?

Best wishes
Xiaohan

**Comment by msbentsen** [comment]
Hi Xiaohan,

Yes, you can use any annotation software you like (I used UROPA for the file in test_data). For BINDetect, the peaks do not have to be annotated - but I recommend to annotate since the additional columns from `--peaks` are transferred to the output TFBS. That makes it easier to interpret the biological significance of the differential binding sites.

Best Mette

**Comment by xiaohanhe2020** [comment]
Dear matte,
Thank you so much. Could you please do me a help to use UROPA to annotate the my file for me?
I just learn coding for two weeks.
I don’t think I will get this work without help.

Many thanks
Xiaohan

On 20 Mar 2020, at 13:01, Mette Bentsen <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Xiaohan,

Yes, you can use any annotation software you like (I used UROPA for the file in test_data). For BINDetect, the peaks do not have to be annotated - but I recommend to annotate since the additional columns from --peaks are transferred to the output TFBS. That makes it easier to interpret the biological significance of the differential binding sites.

Best Mette

**Comment by msbentsen** [comment]
Hi Xiaohan,

I suggest you first spend some time to take a look at the input for UROPA, and try it out yourself ([link to the GitHub repository is here](https://github.com/loosolab/UROPA)). If you are then still unsure of the usage of the tool, you are welcome to open an issue at the UROPA page. It is not that I don't want to help, but it takes longer than 2 weeks to learn bioinformatics - and this is unfortunately not anything I can help you with.

Best Mette

**Comment by xiaohanhe2020** [comment]
Hi Mette,
Thank you for your email.
I try UROPA.
This is my code. But it seems not work well.
## download GTF file
wget ftp://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz<http://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz>
gunzip Homo_sapiens.GRCh37.75.gtf.gz

## download BED file
wget https://www.encodeproject.org/files/ENCFF966LMJ/@@download/ENCFF966LMJ.bed.gz
gunzip ENCFF966LMJ.bed.gz

config.json

'''
{"queries": [        {"feature":"gene", "distance":5000, "feature.anchor": "start", “show.attribute
s":"gene_name"},        {"feature": "gene","distance":5000, "feature.anchor":"center"}],"priority" : "False","gtf": "/home/soft/uropa/Homo_sapiens.GRCh37.75.gtf","bed": "/home/soft/research/uropa/ENCFF966LMJ.bed"}
'''

uropa -I config.json

Do you know the reasons?

Best wishes
Xiaohan

On 20 Mar 2020, at 15:22, Mette Bentsen <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Xiaohan,

I suggest you first spend some time to take a look at the input for UROPA, and try it out yourself (link to the GitHub repository is here<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Floosolab%2FUROPA&data=01%7C01%7Cxiaohan.he%40KCL.ac.uk%7Cd82acc3c9e464628ff4a08d7cce2902e%7C8370cf1416f34c16b83c724071654356%7C0&sdata=K9flv4q%2FeNID%2FJtQRgbXFt6iGZYbwTlSyDt7pvy6qeA%3D&reserved=0>). If you are then still unsure of the usage of the tool, you are welcome to open an issue at the UROPA page. It is not that I don't want to help, but it takes longer than 2 weeks to learn bioinformatics - and this is unfortunately not anything I can help you with.

Best Mette

**Comment by xiaohanhe2020** [comment]
Dear Matte,
Sorry to disturb you.
Could you please send me the config.json file for annotated peaks.bed in the test dataset of Tobias?

Best wishes
Xiaohan

On 21 Mar 2020, at 10:40, He, Xiaohan <xiaohan.he@kcl.ac.uk<mailto:xiaohan.he@kcl.ac.uk>> wrote:

Hi Mette,
Thank you for your email.
I try UROPA.
This is my code. But it seems not work well.
## download GTF file
wget ftp://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz<http://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz>
gunzip Homo_sapiens.GRCh37.75.gtf.gz<x-msg://3/Homo_sapiens.GRCh37.75.gtf.gz>

## download BED file
wget https://www.encodeproject.org/files/ENCFF966LMJ/@@download/ENCFF966LMJ.bed.gz
gunzip ENCFF966LMJ.bed.gz

config.json

'''
{"queries": [        {"feature":"gene", "distance":5000, "feature.anchor": "start", “show.attribute
s":"gene_name"},        {"feature": "gene","distance":5000, "feature.anchor":"center"}],"priority" : "False","gtf": "/home/soft/uropa/Homo_sapiens.GRCh37.75.gtf<x-msg://3/Homo_sapiens.GRCh37.75.gtf>","bed": "/home/soft/research/uropa/ENCFF966LMJ.bed"}
'''

uropa -I config.json

Do you know the reasons?

Best wishes
Xiaohan

On 20 Mar 2020, at 15:22, Mette Bentsen <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Xiaohan,

I suggest you first spend some time to take a look at the input for UROPA, and try it out yourself (link to the GitHub repository is here<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Floosolab%2FUROPA&data=01%7C01%7Cxiaohan.he%40KCL.ac.uk%7Cd82acc3c9e464628ff4a08d7cce2902e%7C8370cf1416f34c16b83c724071654356%7C0&sdata=K9flv4q%2FeNID%2FJtQRgbXFt6iGZYbwTlSyDt7pvy6qeA%3D&reserved=0>). If you are then still unsure of the usage of the tool, you are welcome to open an issue at the UROPA page. It is not that I don't want to help, but it takes longer than 2 weeks to learn bioinformatics - and this is unfortunately not anything I can help you with.

Best Mette

**Comment by msbentsen** [comment]
Hi Xiaohan, 
Please write an issue on the UROPA github issues page if you are having problems with the use of UROPA - thank you! Closing as this is not related to TOBIAS.
