### ISSUE TITLE
Strange aggregate plot

### ISSUE THREAD

**Issue by XiangyuZhangCharlie** [loosolab/TOBIAS#80]
Hi Mette,

Thank you very much for providing this fantastic tool for ATAC-Seq footprinting. However, something strange happened when I was  doing my analysis. Two motifs which I am interested were highlighted as differential binding in treatment in the Bindetect output volcano plot. So I drew the aggregate plot of the two motifs, and they show strange shapes roughly like the two images below:

![Abnormal_Aggregate1](https://user-images.githubusercontent.com/81770775/124026725-07a2f380-d9c0-11eb-9b1c-4e4027849a9b.png)
![Abnormal_Aggregate2](https://user-images.githubusercontent.com/81770775/124026726-083b8a00-d9c0-11eb-8609-4230a6f59762.png)

The two shapes look very different compared to the examples showed in this repository and on the paper, and the y-axis values are less than 1 as well. Is this normal? Or is it problematic? If it is normal, what might be the reason for the difference in the shapes? If it is abnormal, what might have caused this problem?

I followed the ATACCorrect -> FootprintScores steps for my control and treatment data and then used BINDetect to find the differentially binding motifs. I also calculated the signals across the same peaks for all the steps, by using a combined peak file of the two conditions.

Thank you very much,

Best regards,

Xiangyu Zhang

**Comment by msbentsen** [comment]
Hi Xiangyu Zhang,

Not all TFs create great footprints, so it might just be the case that the one TF is within this group. 

However, maybe you can share the commandline commands that you used or the actual plots? That might help me see if there is something wrong. The y-axis values are relative to the specific run, so I can't say whether those are problematic or not. Your approach looks right though!

Best regards,
Mette
