### ISSUE TITLE
TOBIAS DownloadData invalid choice

### ISSUE THREAD

**Issue by lugile1** [loosolab/TOBIAS#81]
Hi, I am trying to download the test data after successful installation of TOBIAS using the TOBIAS environment and I get the following error:

`(TOBIAS_ENV) leonie@lab101leonie:~/TOBIAS$ TOBIAS DownloadData --bucket data-tobias-2020
TOBIAS: error: argument : invalid choice: 'DownloadData' (choose from 'ATACorrect', 'ScoreBigwig', 'FootprintScores', 'BINDetect', 'TFBScan', 'FormatMotifs', 'ScoreBed', 'PlotAggregate', 'PlotHeatmap', 'PlotChanges', 'PlotTracks', 'MergePDF', 'MaxPos', 'SubsampleBam', 'CreateNetwork', 'Log2Table')
`

Any help would be appreciated! Thanks!

**Comment by msbentsen** [comment]
Hi, the `DownloadData` module was added in `TOBIAS 0.11.0` - so please try to update your installation. Then the option should be available. Did you download via conda? I think there have been some problems of it fetching older versions. Let me know how it goes, thanks!

**Comment by lugile1** [comment]
Yes you were right, that was the issue. I had initially used conda to install TOBIAS, but now uninstalled and used pip install instead, all in the TOBIAS environment. Now it seems to be working fine! Thanks a lot for your help, I am very excited to start using TOBIAS with my own data!
