### ISSUE TITLE
Did the cut results of PlotAggregate's has normalized

### ISSUE THREAD

**Issue by 2961461560** [loosolab/TOBIAS#83]
Hi, authors. I have a question to ask. Did the cut number results of PlotAggregate's between samples have normalized? Can I compare footprint between different samples from the picture directly? Thank you! @msbentsen @hschult @afust @pgoymann @mlooso 
this is my command
```
TOBIAS PlotAggregate --TFBS MYB.bed --signals ./tobias/BZ{1..10}/*_corrected.bw --output MYB_footprint.pdf  --output-txt MYB_footprint_cuts.txt --share_y both --plot_boundaries --signal-on-x --flank 250
```
![image](https://user-images.githubusercontent.com/34473055/125186424-f4fcaa00-e25c-11eb-8bc3-6c2bf57c4442.png)

I used corrected cut files made by ATACorrect module, and a bed file containing potential MYB binding sites. then I used the command above to examine footprint of MYB TF in all my samples, so the question is can I compare footprint in all samples directly? ,that is did the cut numbers result of PlotAggregate's between samples have normalized?

**Comment by msbentsen** [comment]
Hi,

If you have run ATACorrect with the same `--peaks` file for all samples, they will be normalized by depth and signal-to-noise ratio, and so can be compared directly to each other! If the `--peaks` are different per run, it is not possible to compare the signals directly. Hope this explanation helps you out.

Best Mette

**Comment by 2961461560** [comment]
Hi, thank you! I performed ATACorrect used the same peaks. @msbentsen
another matter, The bed file used in the command above only contain 3 columns, chr start end, is okay?

**Comment by msbentsen** [comment]
Yes, a 3-column bed-file should be totally fine 👍

**Comment by 2961461560** [comment]
thank you very much @msbentsen
