### ISSUE TITLE
ClusterMotifs not running - problem with gimmemotifs dependency 

### ISSUE THREAD

**Issue by tdarthur40** [loosolab/TOBIAS#88]
Hi, 

I'm trying to run ClusterMotifs on a JASPAR formatted pwm in a TOBIAS conda environment. I get the error message below - even after I pip and conda installed the gimmemotifs package. I'm not sure why gimmemotifs is not being recognized by the command. 

2021-08-19 11:21:05 (20646) [ERROR]	MotifClust requires the python package 'gimmemotifs'. You can install it using 'pip install gimmemotifs' or 'conda install gimmemotifs'.

Any help is appreciated - thanks.

**Comment by msbentsen** [comment]
Hi,

Hmm, yes that does seems a bit weird. Can you confirm that gimmemotifs is installed in the same python distribution that you use for TOBIAS? Also, could you try to open Python on your terminal and run `import gimmemotifs`?

I got an `KeyError: 'params'` on import, so this might be the reason why the gimmemotifs package is not recognized. Please let me know if this is also your issue, then I will try to provide a fix!

**Comment by tdarthur40** [comment]
The packages and environment were both installed with python 3.7. When I try to import the package within the environment it returns: ImportError: cannot import name 'get_active_plugins' from 'genomepy.plugins'.

Thanks!
